// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aws-sns/message.proto

package aws_sns

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/micro/go-micro/api/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TargetARN struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	DeviceType           int32    `protobuf:"varint,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetARN) Reset()         { *m = TargetARN{} }
func (m *TargetARN) String() string { return proto.CompactTextString(m) }
func (*TargetARN) ProtoMessage()    {}
func (*TargetARN) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee65568b2ede44d0, []int{0}
}

func (m *TargetARN) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetARN.Unmarshal(m, b)
}
func (m *TargetARN) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetARN.Marshal(b, m, deterministic)
}
func (m *TargetARN) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetARN.Merge(m, src)
}
func (m *TargetARN) XXX_Size() int {
	return xxx_messageInfo_TargetARN.Size(m)
}
func (m *TargetARN) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetARN.DiscardUnknown(m)
}

var xxx_messageInfo_TargetARN proto.InternalMessageInfo

func (m *TargetARN) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *TargetARN) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

type PublishInput struct {
	Platform             string       `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject              string       `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Message              string       `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Target               []*TargetARN `protobuf:"bytes,5,rep,name=target,proto3" json:"target,omitempty"`
	ClickAction          string       `protobuf:"bytes,6,opt,name=click_action,json=clickAction,proto3" json:"click_action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PublishInput) Reset()         { *m = PublishInput{} }
func (m *PublishInput) String() string { return proto.CompactTextString(m) }
func (*PublishInput) ProtoMessage()    {}
func (*PublishInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee65568b2ede44d0, []int{1}
}

func (m *PublishInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishInput.Unmarshal(m, b)
}
func (m *PublishInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishInput.Marshal(b, m, deterministic)
}
func (m *PublishInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishInput.Merge(m, src)
}
func (m *PublishInput) XXX_Size() int {
	return xxx_messageInfo_PublishInput.Size(m)
}
func (m *PublishInput) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishInput.DiscardUnknown(m)
}

var xxx_messageInfo_PublishInput proto.InternalMessageInfo

func (m *PublishInput) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *PublishInput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PublishInput) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *PublishInput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PublishInput) GetTarget() []*TargetARN {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *PublishInput) GetClickAction() string {
	if m != nil {
		return m.ClickAction
	}
	return ""
}

type PublishOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishOutput) Reset()         { *m = PublishOutput{} }
func (m *PublishOutput) String() string { return proto.CompactTextString(m) }
func (*PublishOutput) ProtoMessage()    {}
func (*PublishOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee65568b2ede44d0, []int{2}
}

func (m *PublishOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishOutput.Unmarshal(m, b)
}
func (m *PublishOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishOutput.Marshal(b, m, deterministic)
}
func (m *PublishOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishOutput.Merge(m, src)
}
func (m *PublishOutput) XXX_Size() int {
	return xxx_messageInfo_PublishOutput.Size(m)
}
func (m *PublishOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishOutput.DiscardUnknown(m)
}

var xxx_messageInfo_PublishOutput proto.InternalMessageInfo

type CreateEndpointRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DeviceType           int32    `protobuf:"varint,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEndpointRequest) Reset()         { *m = CreateEndpointRequest{} }
func (m *CreateEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEndpointRequest) ProtoMessage()    {}
func (*CreateEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee65568b2ede44d0, []int{3}
}

func (m *CreateEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEndpointRequest.Unmarshal(m, b)
}
func (m *CreateEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEndpointRequest.Marshal(b, m, deterministic)
}
func (m *CreateEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEndpointRequest.Merge(m, src)
}
func (m *CreateEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEndpointRequest.Size(m)
}
func (m *CreateEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEndpointRequest proto.InternalMessageInfo

func (m *CreateEndpointRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateEndpointRequest) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

type CreateEndpointResponse struct {
	EndpointArn          string   `protobuf:"bytes,1,opt,name=endpoint_arn,json=endpointArn,proto3" json:"endpoint_arn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEndpointResponse) Reset()         { *m = CreateEndpointResponse{} }
func (m *CreateEndpointResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEndpointResponse) ProtoMessage()    {}
func (*CreateEndpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee65568b2ede44d0, []int{4}
}

func (m *CreateEndpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEndpointResponse.Unmarshal(m, b)
}
func (m *CreateEndpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEndpointResponse.Marshal(b, m, deterministic)
}
func (m *CreateEndpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEndpointResponse.Merge(m, src)
}
func (m *CreateEndpointResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEndpointResponse.Size(m)
}
func (m *CreateEndpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEndpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEndpointResponse proto.InternalMessageInfo

func (m *CreateEndpointResponse) GetEndpointArn() string {
	if m != nil {
		return m.EndpointArn
	}
	return ""
}

func init() {
	proto.RegisterType((*TargetARN)(nil), "aws_sns.TargetARN")
	proto.RegisterType((*PublishInput)(nil), "aws_sns.PublishInput")
	proto.RegisterType((*PublishOutput)(nil), "aws_sns.PublishOutput")
	proto.RegisterType((*CreateEndpointRequest)(nil), "aws_sns.CreateEndpointRequest")
	proto.RegisterType((*CreateEndpointResponse)(nil), "aws_sns.CreateEndpointResponse")
}

func init() {
	proto.RegisterFile("aws-sns/message.proto", fileDescriptor_ee65568b2ede44d0)
}

var fileDescriptor_ee65568b2ede44d0 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0x41, 0xeb, 0xd3, 0x40,
	0x10, 0xc5, 0x89, 0xff, 0x36, 0x6d, 0x27, 0x95, 0xca, 0x62, 0x4b, 0xc8, 0xc1, 0xd6, 0x9c, 0x8a,
	0xd0, 0x04, 0xea, 0x45, 0xf0, 0x14, 0xd4, 0x43, 0x11, 0x6a, 0x49, 0x0b, 0x1e, 0xc3, 0x26, 0x5d,
	0xd3, 0xb5, 0xcd, 0x6e, 0xcc, 0x6e, 0x14, 0xbf, 0x9d, 0x7e, 0x33, 0x93, 0xdd, 0x4d, 0x94, 0xa2,
	0x78, 0x9b, 0xf7, 0x9b, 0xcc, 0xcb, 0xbc, 0x61, 0x61, 0x8e, 0xbf, 0x89, 0x8d, 0x60, 0x22, 0x2c,
	0x88, 0x10, 0x38, 0x27, 0x41, 0x59, 0x71, 0xc9, 0xd1, 0xa8, 0xc1, 0x49, 0x83, 0xbd, 0x4d, 0x4e,
	0xe5, 0xa5, 0x4e, 0x83, 0x8c, 0x17, 0x61, 0x41, 0xb3, 0x8a, 0x87, 0x39, 0xdf, 0xe8, 0x02, 0x97,
	0x34, 0x54, 0x5f, 0xb7, 0x95, 0x9e, 0xf3, 0xdf, 0xc2, 0xe4, 0x84, 0xab, 0x9c, 0xc8, 0x28, 0xde,
	0xa3, 0x05, 0xd8, 0x52, 0x09, 0xd7, 0x5a, 0x59, 0xeb, 0x49, 0x6c, 0x14, 0x5a, 0x82, 0x73, 0x26,
	0x5f, 0x69, 0x46, 0x12, 0xf9, 0xbd, 0x24, 0xee, 0xa3, 0xa6, 0x39, 0x8c, 0x41, 0xa3, 0x53, 0x43,
	0xfc, 0x9f, 0x16, 0x4c, 0x0f, 0x75, 0x7a, 0xa3, 0xe2, 0xb2, 0x63, 0x65, 0x2d, 0x91, 0x07, 0xe3,
	0xf2, 0x86, 0xe5, 0x27, 0x5e, 0x15, 0xc6, 0xab, 0xd7, 0x08, 0xc1, 0x80, 0xe1, 0x42, 0xdb, 0x4c,
	0x62, 0x55, 0x23, 0x17, 0x46, 0xa2, 0x4e, 0x3f, 0x93, 0x4c, 0xba, 0x0f, 0x0a, 0x77, 0xb2, 0xed,
	0x98, 0xa4, 0xee, 0x40, 0x77, 0x8c, 0x44, 0x2f, 0xfa, 0x6d, 0x87, 0xab, 0x87, 0xb5, 0xb3, 0x45,
	0x81, 0xb9, 0x41, 0xd0, 0x27, 0xea, 0x13, 0x3c, 0x87, 0x69, 0x76, 0xa3, 0xd9, 0x35, 0xc1, 0x99,
	0xa4, 0x9c, 0xb9, 0xb6, 0xb2, 0x72, 0x14, 0x8b, 0x14, 0xf2, 0x67, 0xf0, 0xd8, 0x44, 0xf8, 0x50,
	0xcb, 0x26, 0x83, 0xbf, 0x87, 0xf9, 0x9b, 0x8a, 0x60, 0x49, 0xde, 0xb1, 0x73, 0xc9, 0x29, 0x93,
	0x31, 0xf9, 0x52, 0x13, 0x21, 0xd1, 0x53, 0x18, 0x4a, 0x7e, 0x25, 0xcc, 0x24, 0xd3, 0xe2, 0xff,
	0x47, 0x7a, 0x0d, 0x8b, 0x7b, 0x3f, 0x51, 0x72, 0x26, 0x48, 0xbb, 0x1d, 0x31, 0x2c, 0xc1, 0x55,
	0xe7, 0xeb, 0x74, 0x2c, 0xaa, 0xd8, 0xf6, 0x87, 0x05, 0x76, 0xf4, 0xf1, 0x78, 0xdc, 0x1f, 0xd1,
	0x2b, 0x18, 0x99, 0x45, 0xd1, 0xbc, 0x8f, 0xfc, 0xe7, 0xf5, 0xbd, 0xc5, 0x3d, 0xd6, 0x89, 0xd0,
	0x7b, 0x18, 0x77, 0xff, 0x46, 0xcf, 0xfa, 0x6f, 0xfe, 0x1a, 0xd2, 0x5b, 0xfe, 0xb3, 0x6f, 0x96,
	0x0e, 0x01, 0x8c, 0x7b, 0x74, 0xd8, 0xa1, 0x59, 0x90, 0xf3, 0xa0, 0x7d, 0x56, 0xdd, 0xfc, 0x93,
	0xdf, 0x40, 0x0f, 0xa4, 0xb6, 0x7a, 0x71, 0x2f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x2d,
	0x3e, 0x0d, 0xc2, 0x02, 0x00, 0x00,
}
