// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment/message.proto

package message

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/micro/go-micro/api/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CoinRequest struct {
	CustomerNumber       string   `protobuf:"bytes,1,opt,name=CustomerNumber,proto3" json:"CustomerNumber,omitempty"`
	Coin                 uint64   `protobuf:"varint,2,opt,name=Coin,proto3" json:"Coin,omitempty"`
	Currency             string   `protobuf:"bytes,3,opt,name=Currency,proto3" json:"Currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinRequest) Reset()         { *m = CoinRequest{} }
func (m *CoinRequest) String() string { return proto.CompactTextString(m) }
func (*CoinRequest) ProtoMessage()    {}
func (*CoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{0}
}

func (m *CoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinRequest.Unmarshal(m, b)
}
func (m *CoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinRequest.Marshal(b, m, deterministic)
}
func (m *CoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinRequest.Merge(m, src)
}
func (m *CoinRequest) XXX_Size() int {
	return xxx_messageInfo_CoinRequest.Size(m)
}
func (m *CoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoinRequest proto.InternalMessageInfo

func (m *CoinRequest) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *CoinRequest) GetCoin() uint64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *CoinRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type StatusCodeResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusCodeResponse) Reset()         { *m = StatusCodeResponse{} }
func (m *StatusCodeResponse) String() string { return proto.CompactTextString(m) }
func (*StatusCodeResponse) ProtoMessage()    {}
func (*StatusCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{1}
}

func (m *StatusCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusCodeResponse.Unmarshal(m, b)
}
func (m *StatusCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusCodeResponse.Marshal(b, m, deterministic)
}
func (m *StatusCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusCodeResponse.Merge(m, src)
}
func (m *StatusCodeResponse) XXX_Size() int {
	return xxx_messageInfo_StatusCodeResponse.Size(m)
}
func (m *StatusCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusCodeResponse proto.InternalMessageInfo

func (m *StatusCodeResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GetWalletInfoRequest struct {
	CustomerNumber       string   `protobuf:"bytes,1,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletInfoRequest) Reset()         { *m = GetWalletInfoRequest{} }
func (m *GetWalletInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetWalletInfoRequest) ProtoMessage()    {}
func (*GetWalletInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{2}
}

func (m *GetWalletInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletInfoRequest.Unmarshal(m, b)
}
func (m *GetWalletInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetWalletInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletInfoRequest.Merge(m, src)
}
func (m *GetWalletInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetWalletInfoRequest.Size(m)
}
func (m *GetWalletInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletInfoRequest proto.InternalMessageInfo

func (m *GetWalletInfoRequest) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *GetWalletInfoRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type GetWalletInfoResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletInfoResponse) Reset()         { *m = GetWalletInfoResponse{} }
func (m *GetWalletInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetWalletInfoResponse) ProtoMessage()    {}
func (*GetWalletInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{3}
}

func (m *GetWalletInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletInfoResponse.Unmarshal(m, b)
}
func (m *GetWalletInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetWalletInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletInfoResponse.Merge(m, src)
}
func (m *GetWalletInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetWalletInfoResponse.Size(m)
}
func (m *GetWalletInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletInfoResponse proto.InternalMessageInfo

func (m *GetWalletInfoResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetWalletInfoResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type CreateTransactionRequest struct {
	Amount               uint64   `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	CurrencyCode         string   `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	TransactionMethod    string   `protobuf:"bytes,3,opt,name=transaction_method,json=transactionMethod,proto3" json:"transaction_method,omitempty"`
	UserUuid             string   `protobuf:"bytes,4,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CustomerNumber       string   `protobuf:"bytes,5,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	Service              string   `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`
	Metadata             string   `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TransactionDetail    string   `protobuf:"bytes,8,opt,name=transaction_detail,json=transactionDetail,proto3" json:"transaction_detail,omitempty"`
	Agent                string   `protobuf:"bytes,9,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTransactionRequest) Reset()         { *m = CreateTransactionRequest{} }
func (m *CreateTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTransactionRequest) ProtoMessage()    {}
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{4}
}

func (m *CreateTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTransactionRequest.Unmarshal(m, b)
}
func (m *CreateTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTransactionRequest.Marshal(b, m, deterministic)
}
func (m *CreateTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTransactionRequest.Merge(m, src)
}
func (m *CreateTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTransactionRequest.Size(m)
}
func (m *CreateTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTransactionRequest proto.InternalMessageInfo

func (m *CreateTransactionRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreateTransactionRequest) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *CreateTransactionRequest) GetTransactionMethod() string {
	if m != nil {
		return m.TransactionMethod
	}
	return ""
}

func (m *CreateTransactionRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *CreateTransactionRequest) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *CreateTransactionRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *CreateTransactionRequest) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *CreateTransactionRequest) GetTransactionDetail() string {
	if m != nil {
		return m.TransactionDetail
	}
	return ""
}

func (m *CreateTransactionRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

type CreateTransactionResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTransactionResponse) Reset()         { *m = CreateTransactionResponse{} }
func (m *CreateTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTransactionResponse) ProtoMessage()    {}
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{5}
}

func (m *CreateTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTransactionResponse.Unmarshal(m, b)
}
func (m *CreateTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTransactionResponse.Marshal(b, m, deterministic)
}
func (m *CreateTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTransactionResponse.Merge(m, src)
}
func (m *CreateTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTransactionResponse.Size(m)
}
func (m *CreateTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTransactionResponse proto.InternalMessageInfo

func (m *CreateTransactionResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type GetRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{6}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code                 int64    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{7}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *GetResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type GetTransactionHistoryRequest struct {
	CustomerNumber       string   `protobuf:"bytes,1,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionHistoryRequest) Reset()         { *m = GetTransactionHistoryRequest{} }
func (m *GetTransactionHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionHistoryRequest) ProtoMessage()    {}
func (*GetTransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{8}
}

func (m *GetTransactionHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionHistoryRequest.Unmarshal(m, b)
}
func (m *GetTransactionHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionHistoryRequest.Merge(m, src)
}
func (m *GetTransactionHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionHistoryRequest.Size(m)
}
func (m *GetTransactionHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionHistoryRequest proto.InternalMessageInfo

func (m *GetTransactionHistoryRequest) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

type UpdateSubscriptionRequest struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Duration             uint32               `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Status               uint32               `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	ChargeDate           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=charge_date,json=chargeDate,proto3" json:"charge_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateSubscriptionRequest) Reset()         { *m = UpdateSubscriptionRequest{} }
func (m *UpdateSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSubscriptionRequest) ProtoMessage()    {}
func (*UpdateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{9}
}

func (m *UpdateSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSubscriptionRequest.Unmarshal(m, b)
}
func (m *UpdateSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSubscriptionRequest.Merge(m, src)
}
func (m *UpdateSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSubscriptionRequest.Size(m)
}
func (m *UpdateSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSubscriptionRequest proto.InternalMessageInfo

func (m *UpdateSubscriptionRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateSubscriptionRequest) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *UpdateSubscriptionRequest) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateSubscriptionRequest) GetChargeDate() *timestamp.Timestamp {
	if m != nil {
		return m.ChargeDate
	}
	return nil
}

type UpdateSubscriptionResponse struct {
	Code                 uint64   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSubscriptionResponse) Reset()         { *m = UpdateSubscriptionResponse{} }
func (m *UpdateSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSubscriptionResponse) ProtoMessage()    {}
func (*UpdateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{10}
}

func (m *UpdateSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSubscriptionResponse.Unmarshal(m, b)
}
func (m *UpdateSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSubscriptionResponse.Merge(m, src)
}
func (m *UpdateSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSubscriptionResponse.Size(m)
}
func (m *UpdateSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSubscriptionResponse proto.InternalMessageInfo

func (m *UpdateSubscriptionResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type CreateSubRequest struct {
	PackageUuid          string   `protobuf:"bytes,1,opt,name=package_uuid,json=packageUuid,proto3" json:"package_uuid,omitempty"`
	CustomerNumber       string   `protobuf:"bytes,2,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Duration             uint32   `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	PromoCode            string   `protobuf:"bytes,5,opt,name=promo_code,json=promoCode,proto3" json:"promo_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubRequest) Reset()         { *m = CreateSubRequest{} }
func (m *CreateSubRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSubRequest) ProtoMessage()    {}
func (*CreateSubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{11}
}

func (m *CreateSubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubRequest.Unmarshal(m, b)
}
func (m *CreateSubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubRequest.Marshal(b, m, deterministic)
}
func (m *CreateSubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubRequest.Merge(m, src)
}
func (m *CreateSubRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSubRequest.Size(m)
}
func (m *CreateSubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubRequest proto.InternalMessageInfo

func (m *CreateSubRequest) GetPackageUuid() string {
	if m != nil {
		return m.PackageUuid
	}
	return ""
}

func (m *CreateSubRequest) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *CreateSubRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *CreateSubRequest) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *CreateSubRequest) GetPromoCode() string {
	if m != nil {
		return m.PromoCode
	}
	return ""
}

type CacheField struct {
	CustomerNumber       string   `protobuf:"bytes,1,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	PackageUuid          string   `protobuf:"bytes,3,opt,name=package_uuid,json=packageUuid,proto3" json:"package_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheField) Reset()         { *m = CacheField{} }
func (m *CacheField) String() string { return proto.CompactTextString(m) }
func (*CacheField) ProtoMessage()    {}
func (*CacheField) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{12}
}

func (m *CacheField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheField.Unmarshal(m, b)
}
func (m *CacheField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheField.Marshal(b, m, deterministic)
}
func (m *CacheField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheField.Merge(m, src)
}
func (m *CacheField) XXX_Size() int {
	return xxx_messageInfo_CacheField.Size(m)
}
func (m *CacheField) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheField.DiscardUnknown(m)
}

var xxx_messageInfo_CacheField proto.InternalMessageInfo

func (m *CacheField) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *CacheField) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *CacheField) GetPackageUuid() string {
	if m != nil {
		return m.PackageUuid
	}
	return ""
}

type GetDetailRequest struct {
	// Types that are valid to be assigned to Request:
	//	*GetDetailRequest_Uuid
	//	*GetDetailRequest_Field
	Request              isGetDetailRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetDetailRequest) Reset()         { *m = GetDetailRequest{} }
func (m *GetDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetDetailRequest) ProtoMessage()    {}
func (*GetDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{13}
}

func (m *GetDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDetailRequest.Unmarshal(m, b)
}
func (m *GetDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDetailRequest.Marshal(b, m, deterministic)
}
func (m *GetDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDetailRequest.Merge(m, src)
}
func (m *GetDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetDetailRequest.Size(m)
}
func (m *GetDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDetailRequest proto.InternalMessageInfo

type isGetDetailRequest_Request interface {
	isGetDetailRequest_Request()
}

type GetDetailRequest_Uuid struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3,oneof"`
}

type GetDetailRequest_Field struct {
	Field *CacheField `protobuf:"bytes,2,opt,name=field,proto3,oneof"`
}

func (*GetDetailRequest_Uuid) isGetDetailRequest_Request() {}

func (*GetDetailRequest_Field) isGetDetailRequest_Request() {}

func (m *GetDetailRequest) GetRequest() isGetDetailRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *GetDetailRequest) GetUuid() string {
	if x, ok := m.GetRequest().(*GetDetailRequest_Uuid); ok {
		return x.Uuid
	}
	return ""
}

func (m *GetDetailRequest) GetField() *CacheField {
	if x, ok := m.GetRequest().(*GetDetailRequest_Field); ok {
		return x.Field
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetDetailRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetDetailRequest_Uuid)(nil),
		(*GetDetailRequest_Field)(nil),
	}
}

type GetSubscriptionsRequest struct {
	PackageUuid          string   `protobuf:"bytes,1,opt,name=package_uuid,json=packageUuid,proto3" json:"package_uuid,omitempty"`
	CustomerNumber       string   `protobuf:"bytes,2,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubscriptionsRequest) Reset()         { *m = GetSubscriptionsRequest{} }
func (m *GetSubscriptionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSubscriptionsRequest) ProtoMessage()    {}
func (*GetSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{14}
}

func (m *GetSubscriptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscriptionsRequest.Unmarshal(m, b)
}
func (m *GetSubscriptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscriptionsRequest.Marshal(b, m, deterministic)
}
func (m *GetSubscriptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscriptionsRequest.Merge(m, src)
}
func (m *GetSubscriptionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSubscriptionsRequest.Size(m)
}
func (m *GetSubscriptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscriptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscriptionsRequest proto.InternalMessageInfo

func (m *GetSubscriptionsRequest) GetPackageUuid() string {
	if m != nil {
		return m.PackageUuid
	}
	return ""
}

func (m *GetSubscriptionsRequest) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

type GetSubscriptionsResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code                 int64    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubscriptionsResponse) Reset()         { *m = GetSubscriptionsResponse{} }
func (m *GetSubscriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSubscriptionsResponse) ProtoMessage()    {}
func (*GetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{15}
}

func (m *GetSubscriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscriptionsResponse.Unmarshal(m, b)
}
func (m *GetSubscriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscriptionsResponse.Marshal(b, m, deterministic)
}
func (m *GetSubscriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscriptionsResponse.Merge(m, src)
}
func (m *GetSubscriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSubscriptionsResponse.Size(m)
}
func (m *GetSubscriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscriptionsResponse proto.InternalMessageInfo

func (m *GetSubscriptionsResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *GetSubscriptionsResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type GetDetailResponse struct {
	StartDate *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	PackageId string               `protobuf:"bytes,3,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Type      uint32               `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	// string  meta = 5;
	Duration       uint32 `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	IntervalTime   uint32 `protobuf:"varint,6,opt,name=interval_time,json=intervalTime,proto3" json:"interval_time,omitempty"`
	Quota          uint32 `protobuf:"varint,7,opt,name=quota,proto3" json:"quota,omitempty"`
	Price          uint64 `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	CustomerNumber string `protobuf:"bytes,9,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	// string  service = 11;
	Status           uint32 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	HaveTrialPackage bool   `protobuf:"varint,11,opt,name=have_trial_package,json=haveTrialPackage,proto3" json:"have_trial_package,omitempty"`
	TrialDuration    string `protobuf:"bytes,12,opt,name=trial_duration,json=trialDuration,proto3" json:"trial_duration,omitempty"`
	StatusName       string `protobuf:"bytes,13,opt,name=status_name,json=statusName,proto3" json:"status_name,omitempty"`
	// string  token = 14;
	// string card_customer_id = 15;
	Uuid                 string               `protobuf:"bytes,14,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ChargeDate           *timestamp.Timestamp `protobuf:"bytes,15,opt,name=charge_date,json=chargeDate,proto3" json:"charge_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDetailResponse) Reset()         { *m = GetDetailResponse{} }
func (m *GetDetailResponse) String() string { return proto.CompactTextString(m) }
func (*GetDetailResponse) ProtoMessage()    {}
func (*GetDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{16}
}

func (m *GetDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDetailResponse.Unmarshal(m, b)
}
func (m *GetDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDetailResponse.Marshal(b, m, deterministic)
}
func (m *GetDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDetailResponse.Merge(m, src)
}
func (m *GetDetailResponse) XXX_Size() int {
	return xxx_messageInfo_GetDetailResponse.Size(m)
}
func (m *GetDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDetailResponse proto.InternalMessageInfo

func (m *GetDetailResponse) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *GetDetailResponse) GetEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *GetDetailResponse) GetPackageId() string {
	if m != nil {
		return m.PackageId
	}
	return ""
}

func (m *GetDetailResponse) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GetDetailResponse) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *GetDetailResponse) GetIntervalTime() uint32 {
	if m != nil {
		return m.IntervalTime
	}
	return 0
}

func (m *GetDetailResponse) GetQuota() uint32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *GetDetailResponse) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GetDetailResponse) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *GetDetailResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetDetailResponse) GetHaveTrialPackage() bool {
	if m != nil {
		return m.HaveTrialPackage
	}
	return false
}

func (m *GetDetailResponse) GetTrialDuration() string {
	if m != nil {
		return m.TrialDuration
	}
	return ""
}

func (m *GetDetailResponse) GetStatusName() string {
	if m != nil {
		return m.StatusName
	}
	return ""
}

func (m *GetDetailResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetDetailResponse) GetChargeDate() *timestamp.Timestamp {
	if m != nil {
		return m.ChargeDate
	}
	return nil
}

type GetListRequest struct {
	CustomerNumber       string   `protobuf:"bytes,1,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListRequest) Reset()         { *m = GetListRequest{} }
func (m *GetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetListRequest) ProtoMessage()    {}
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{17}
}

func (m *GetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRequest.Unmarshal(m, b)
}
func (m *GetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRequest.Marshal(b, m, deterministic)
}
func (m *GetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRequest.Merge(m, src)
}
func (m *GetListRequest) XXX_Size() int {
	return xxx_messageInfo_GetListRequest.Size(m)
}
func (m *GetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRequest proto.InternalMessageInfo

func (m *GetListRequest) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

type ListResponse struct {
	StartDate            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	PackageId            string               `protobuf:"bytes,3,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Price                uint64               `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Service              string               `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	Status               uint32               `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	StatusName           string               `protobuf:"bytes,7,opt,name=statusName,proto3" json:"statusName,omitempty"`
	IntervalTime         uint32               `protobuf:"varint,8,opt,name=interval_time,json=intervalTime,proto3" json:"interval_time,omitempty"`
	ChargeDate           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=charge_date,json=chargeDate,proto3" json:"charge_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{18}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *ListResponse) GetEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *ListResponse) GetPackageId() string {
	if m != nil {
		return m.PackageId
	}
	return ""
}

func (m *ListResponse) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ListResponse) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ListResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListResponse) GetStatusName() string {
	if m != nil {
		return m.StatusName
	}
	return ""
}

func (m *ListResponse) GetIntervalTime() uint32 {
	if m != nil {
		return m.IntervalTime
	}
	return 0
}

func (m *ListResponse) GetChargeDate() *timestamp.Timestamp {
	if m != nil {
		return m.ChargeDate
	}
	return nil
}

type GetListResponse struct {
	Data                 []*ListResponse `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetListResponse) Reset()         { *m = GetListResponse{} }
func (m *GetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetListResponse) ProtoMessage()    {}
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{19}
}

func (m *GetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResponse.Unmarshal(m, b)
}
func (m *GetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResponse.Marshal(b, m, deterministic)
}
func (m *GetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResponse.Merge(m, src)
}
func (m *GetListResponse) XXX_Size() int {
	return xxx_messageInfo_GetListResponse.Size(m)
}
func (m *GetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResponse proto.InternalMessageInfo

func (m *GetListResponse) GetData() []*ListResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetPackagesRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PromoCode            string   `protobuf:"bytes,2,opt,name=promo_code,json=promoCode,proto3" json:"promo_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPackagesRequest) Reset()         { *m = GetPackagesRequest{} }
func (m *GetPackagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPackagesRequest) ProtoMessage()    {}
func (*GetPackagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{20}
}

func (m *GetPackagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPackagesRequest.Unmarshal(m, b)
}
func (m *GetPackagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPackagesRequest.Marshal(b, m, deterministic)
}
func (m *GetPackagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPackagesRequest.Merge(m, src)
}
func (m *GetPackagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPackagesRequest.Size(m)
}
func (m *GetPackagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPackagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPackagesRequest proto.InternalMessageInfo

func (m *GetPackagesRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetPackagesRequest) GetPromoCode() string {
	if m != nil {
		return m.PromoCode
	}
	return ""
}

type Promotion struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                 uint32               `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Value                uint64               `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	StartDate            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamp.Timestamp `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Meta                 string               `protobuf:"bytes,8,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Promotion) Reset()         { *m = Promotion{} }
func (m *Promotion) String() string { return proto.CompactTextString(m) }
func (*Promotion) ProtoMessage()    {}
func (*Promotion) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{21}
}

func (m *Promotion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Promotion.Unmarshal(m, b)
}
func (m *Promotion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Promotion.Marshal(b, m, deterministic)
}
func (m *Promotion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Promotion.Merge(m, src)
}
func (m *Promotion) XXX_Size() int {
	return xxx_messageInfo_Promotion.Size(m)
}
func (m *Promotion) XXX_DiscardUnknown() {
	xxx_messageInfo_Promotion.DiscardUnknown(m)
}

var xxx_messageInfo_Promotion proto.InternalMessageInfo

func (m *Promotion) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Promotion) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Promotion) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Promotion) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Promotion) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Promotion) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *Promotion) GetEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *Promotion) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

type GetPackagesResponse struct {
	StartDate            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Price                uint64               `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Active               bool                 `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Type                 uint32               `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	CustomerNumber       string               `protobuf:"bytes,6,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	Meta                 string               `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	HaveTrialPackage     bool                 `protobuf:"varint,8,opt,name=have_trial_package,json=haveTrialPackage,proto3" json:"have_trial_package,omitempty"`
	TrialDuration        string               `protobuf:"bytes,9,opt,name=trial_duration,json=trialDuration,proto3" json:"trial_duration,omitempty"`
	IntervalTime         uint32               `protobuf:"varint,10,opt,name=interval_time,json=intervalTime,proto3" json:"interval_time,omitempty"`
	Quota                uint32               `protobuf:"varint,11,opt,name=quota,proto3" json:"quota,omitempty"`
	Duration             uint32               `protobuf:"varint,12,opt,name=duration,proto3" json:"duration,omitempty"`
	ServiceName          string               `protobuf:"bytes,13,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Currency             string               `protobuf:"bytes,14,opt,name=currency,proto3" json:"currency,omitempty"`
	Promotion            *Promotion           `protobuf:"bytes,15,opt,name=promotion,proto3" json:"promotion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetPackagesResponse) Reset()         { *m = GetPackagesResponse{} }
func (m *GetPackagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetPackagesResponse) ProtoMessage()    {}
func (*GetPackagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{22}
}

func (m *GetPackagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPackagesResponse.Unmarshal(m, b)
}
func (m *GetPackagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPackagesResponse.Marshal(b, m, deterministic)
}
func (m *GetPackagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPackagesResponse.Merge(m, src)
}
func (m *GetPackagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetPackagesResponse.Size(m)
}
func (m *GetPackagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPackagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPackagesResponse proto.InternalMessageInfo

func (m *GetPackagesResponse) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *GetPackagesResponse) GetEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *GetPackagesResponse) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GetPackagesResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *GetPackagesResponse) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GetPackagesResponse) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *GetPackagesResponse) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *GetPackagesResponse) GetHaveTrialPackage() bool {
	if m != nil {
		return m.HaveTrialPackage
	}
	return false
}

func (m *GetPackagesResponse) GetTrialDuration() string {
	if m != nil {
		return m.TrialDuration
	}
	return ""
}

func (m *GetPackagesResponse) GetIntervalTime() uint32 {
	if m != nil {
		return m.IntervalTime
	}
	return 0
}

func (m *GetPackagesResponse) GetQuota() uint32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *GetPackagesResponse) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *GetPackagesResponse) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *GetPackagesResponse) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetPackagesResponse) GetPromotion() *Promotion {
	if m != nil {
		return m.Promotion
	}
	return nil
}

type UUIDRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUIDRequest) Reset()         { *m = UUIDRequest{} }
func (m *UUIDRequest) String() string { return proto.CompactTextString(m) }
func (*UUIDRequest) ProtoMessage()    {}
func (*UUIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{23}
}

func (m *UUIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUIDRequest.Unmarshal(m, b)
}
func (m *UUIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUIDRequest.Marshal(b, m, deterministic)
}
func (m *UUIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUIDRequest.Merge(m, src)
}
func (m *UUIDRequest) XXX_Size() int {
	return xxx_messageInfo_UUIDRequest.Size(m)
}
func (m *UUIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UUIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UUIDRequest proto.InternalMessageInfo

func (m *UUIDRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type MessageResponse struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{24}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

type PaymentGatewayRequest struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	MethodName           string                 `protobuf:"bytes,3,opt,name=methodName,proto3" json:"methodName,omitempty"`
	MethodType           uint32                 `protobuf:"varint,4,opt,name=methodType,proto3" json:"methodType,omitempty"`
	MethodURL            string                 `protobuf:"bytes,5,opt,name=methodURL,proto3" json:"methodURL,omitempty"`
	Active               bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	HttpType             int32                  `protobuf:"varint,7,opt,name=http_type,json=httpType,proto3" json:"http_type,omitempty"`
	Param                []*PaymentGatewayParam `protobuf:"bytes,8,rep,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PaymentGatewayRequest) Reset()         { *m = PaymentGatewayRequest{} }
func (m *PaymentGatewayRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentGatewayRequest) ProtoMessage()    {}
func (*PaymentGatewayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{25}
}

func (m *PaymentGatewayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentGatewayRequest.Unmarshal(m, b)
}
func (m *PaymentGatewayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentGatewayRequest.Marshal(b, m, deterministic)
}
func (m *PaymentGatewayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentGatewayRequest.Merge(m, src)
}
func (m *PaymentGatewayRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentGatewayRequest.Size(m)
}
func (m *PaymentGatewayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentGatewayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentGatewayRequest proto.InternalMessageInfo

func (m *PaymentGatewayRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PaymentGatewayRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PaymentGatewayRequest) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *PaymentGatewayRequest) GetMethodType() uint32 {
	if m != nil {
		return m.MethodType
	}
	return 0
}

func (m *PaymentGatewayRequest) GetMethodURL() string {
	if m != nil {
		return m.MethodURL
	}
	return ""
}

func (m *PaymentGatewayRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *PaymentGatewayRequest) GetHttpType() int32 {
	if m != nil {
		return m.HttpType
	}
	return 0
}

func (m *PaymentGatewayRequest) GetParam() []*PaymentGatewayParam {
	if m != nil {
		return m.Param
	}
	return nil
}

type PaymentGatewayResponse struct {
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Uuid                 string                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	MethodName           string                 `protobuf:"bytes,7,opt,name=methodName,proto3" json:"methodName,omitempty"`
	MethodType           string                 `protobuf:"bytes,8,opt,name=methodType,proto3" json:"methodType,omitempty"`
	MethodURL            string                 `protobuf:"bytes,9,opt,name=methodURL,proto3" json:"methodURL,omitempty"`
	Active               bool                   `protobuf:"varint,10,opt,name=active,proto3" json:"active,omitempty"`
	HttpType             string                 `protobuf:"bytes,11,opt,name=http_type,json=httpType,proto3" json:"http_type,omitempty"`
	Param                []*PaymentGatewayParam `protobuf:"bytes,12,rep,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PaymentGatewayResponse) Reset()         { *m = PaymentGatewayResponse{} }
func (m *PaymentGatewayResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentGatewayResponse) ProtoMessage()    {}
func (*PaymentGatewayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{26}
}

func (m *PaymentGatewayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentGatewayResponse.Unmarshal(m, b)
}
func (m *PaymentGatewayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentGatewayResponse.Marshal(b, m, deterministic)
}
func (m *PaymentGatewayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentGatewayResponse.Merge(m, src)
}
func (m *PaymentGatewayResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentGatewayResponse.Size(m)
}
func (m *PaymentGatewayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentGatewayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentGatewayResponse proto.InternalMessageInfo

func (m *PaymentGatewayResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PaymentGatewayResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *PaymentGatewayResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *PaymentGatewayResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PaymentGatewayResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PaymentGatewayResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PaymentGatewayResponse) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *PaymentGatewayResponse) GetMethodType() string {
	if m != nil {
		return m.MethodType
	}
	return ""
}

func (m *PaymentGatewayResponse) GetMethodURL() string {
	if m != nil {
		return m.MethodURL
	}
	return ""
}

func (m *PaymentGatewayResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *PaymentGatewayResponse) GetHttpType() string {
	if m != nil {
		return m.HttpType
	}
	return ""
}

func (m *PaymentGatewayResponse) GetParam() []*PaymentGatewayParam {
	if m != nil {
		return m.Param
	}
	return nil
}

type PaymentGatewayParam struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentGatewayParam) Reset()         { *m = PaymentGatewayParam{} }
func (m *PaymentGatewayParam) String() string { return proto.CompactTextString(m) }
func (*PaymentGatewayParam) ProtoMessage()    {}
func (*PaymentGatewayParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{27}
}

func (m *PaymentGatewayParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentGatewayParam.Unmarshal(m, b)
}
func (m *PaymentGatewayParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentGatewayParam.Marshal(b, m, deterministic)
}
func (m *PaymentGatewayParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentGatewayParam.Merge(m, src)
}
func (m *PaymentGatewayParam) XXX_Size() int {
	return xxx_messageInfo_PaymentGatewayParam.Size(m)
}
func (m *PaymentGatewayParam) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentGatewayParam.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentGatewayParam proto.InternalMessageInfo

func (m *PaymentGatewayParam) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PaymentGatewayParam) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PaymentGatewayParam) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ListPaymentGatewaysResponse struct {
	Data                 []*PaymentGatewayResponse `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListPaymentGatewaysResponse) Reset()         { *m = ListPaymentGatewaysResponse{} }
func (m *ListPaymentGatewaysResponse) String() string { return proto.CompactTextString(m) }
func (*ListPaymentGatewaysResponse) ProtoMessage()    {}
func (*ListPaymentGatewaysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1adbb397249fab38, []int{28}
}

func (m *ListPaymentGatewaysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPaymentGatewaysResponse.Unmarshal(m, b)
}
func (m *ListPaymentGatewaysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPaymentGatewaysResponse.Marshal(b, m, deterministic)
}
func (m *ListPaymentGatewaysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPaymentGatewaysResponse.Merge(m, src)
}
func (m *ListPaymentGatewaysResponse) XXX_Size() int {
	return xxx_messageInfo_ListPaymentGatewaysResponse.Size(m)
}
func (m *ListPaymentGatewaysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPaymentGatewaysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPaymentGatewaysResponse proto.InternalMessageInfo

func (m *ListPaymentGatewaysResponse) GetData() []*PaymentGatewayResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CoinRequest)(nil), "CoinRequest")
	proto.RegisterType((*StatusCodeResponse)(nil), "StatusCodeResponse")
	proto.RegisterType((*GetWalletInfoRequest)(nil), "GetWalletInfoRequest")
	proto.RegisterType((*GetWalletInfoResponse)(nil), "GetWalletInfoResponse")
	proto.RegisterType((*CreateTransactionRequest)(nil), "CreateTransactionRequest")
	proto.RegisterType((*CreateTransactionResponse)(nil), "CreateTransactionResponse")
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*GetTransactionHistoryRequest)(nil), "GetTransactionHistoryRequest")
	proto.RegisterType((*UpdateSubscriptionRequest)(nil), "UpdateSubscriptionRequest")
	proto.RegisterType((*UpdateSubscriptionResponse)(nil), "UpdateSubscriptionResponse")
	proto.RegisterType((*CreateSubRequest)(nil), "CreateSubRequest")
	proto.RegisterType((*CacheField)(nil), "CacheField")
	proto.RegisterType((*GetDetailRequest)(nil), "GetDetailRequest")
	proto.RegisterType((*GetSubscriptionsRequest)(nil), "GetSubscriptionsRequest")
	proto.RegisterType((*GetSubscriptionsResponse)(nil), "GetSubscriptionsResponse")
	proto.RegisterType((*GetDetailResponse)(nil), "GetDetailResponse")
	proto.RegisterType((*GetListRequest)(nil), "GetListRequest")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
	proto.RegisterType((*GetListResponse)(nil), "GetListResponse")
	proto.RegisterType((*GetPackagesRequest)(nil), "GetPackagesRequest")
	proto.RegisterType((*Promotion)(nil), "Promotion")
	proto.RegisterType((*GetPackagesResponse)(nil), "GetPackagesResponse")
	proto.RegisterType((*UUIDRequest)(nil), "UUIDRequest")
	proto.RegisterType((*MessageResponse)(nil), "MessageResponse")
	proto.RegisterType((*PaymentGatewayRequest)(nil), "PaymentGatewayRequest")
	proto.RegisterType((*PaymentGatewayResponse)(nil), "PaymentGatewayResponse")
	proto.RegisterType((*PaymentGatewayParam)(nil), "PaymentGatewayParam")
	proto.RegisterType((*ListPaymentGatewaysResponse)(nil), "ListPaymentGatewaysResponse")
}

func init() { proto.RegisterFile("payment/message.proto", fileDescriptor_1adbb397249fab38) }

var fileDescriptor_1adbb397249fab38 = []byte{
	// 1998 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x59, 0xcd, 0x6f, 0xdb, 0xc8,
	0x15, 0xb7, 0xa8, 0xef, 0x27, 0xc9, 0x1f, 0x63, 0xc7, 0x51, 0x94, 0xec, 0x26, 0x61, 0xd0, 0x6e,
	0x90, 0x34, 0xe3, 0xac, 0xb6, 0x09, 0xda, 0x2e, 0xba, 0x40, 0x24, 0x37, 0xd9, 0xa4, 0x9b, 0x85,
	0x97, 0x89, 0xd1, 0x43, 0x0f, 0x02, 0x2d, 0x8d, 0x65, 0x22, 0x12, 0xa9, 0xa5, 0x48, 0x2f, 0x8c,
	0xfe, 0x01, 0xbd, 0xf4, 0xd8, 0x43, 0x81, 0x5e, 0x7b, 0x2a, 0x50, 0x60, 0xff, 0x91, 0xde, 0x7b,
	0xec, 0xb5, 0xa7, 0xde, 0x8a, 0x22, 0xa7, 0xbe, 0xf9, 0x20, 0x39, 0xa4, 0x28, 0x5b, 0xca, 0xa5,
	0x7b, 0xe3, 0x7c, 0xbc, 0x99, 0x37, 0xbf, 0xf7, 0x7b, 0xbf, 0xf9, 0x20, 0x5c, 0x9b, 0xd9, 0x17,
	0x53, 0xe6, 0x06, 0x07, 0x53, 0x36, 0x9f, 0xdb, 0x63, 0x46, 0x67, 0xbe, 0x17, 0x78, 0x9d, 0xeb,
	0xe7, 0xf6, 0xc4, 0x19, 0xd9, 0x01, 0x3b, 0x88, 0x3e, 0x54, 0xc3, 0xed, 0xb1, 0xe7, 0x8d, 0x27,
	0xec, 0x40, 0x94, 0x4e, 0xc2, 0xd3, 0x83, 0xc0, 0x41, 0xcb, 0xc0, 0x9e, 0xce, 0x54, 0x87, 0x47,
	0x63, 0x27, 0x38, 0x0b, 0x4f, 0xe8, 0xd0, 0x9b, 0x1e, 0x4c, 0x9d, 0xa1, 0xef, 0x1d, 0x8c, 0xbd,
	0x47, 0xf2, 0xc3, 0x9e, 0x39, 0xd2, 0x8e, 0x7f, 0xa9, 0xee, 0x37, 0xb3, 0xe3, 0xb1, 0xe9, 0x2c,
	0xb8, 0x90, 0x8d, 0x26, 0x83, 0x46, 0xdf, 0x73, 0x5c, 0x8b, 0x7d, 0x1b, 0xe2, 0x1c, 0xe4, 0xc7,
	0xb0, 0xd9, 0x0f, 0xe7, 0x81, 0x37, 0x65, 0xfe, 0xd7, 0xe1, 0xf4, 0x84, 0xf9, 0xed, 0xc2, 0x9d,
	0xc2, 0xfd, 0xba, 0x95, 0xa9, 0x25, 0x04, 0x4a, 0xdc, 0xac, 0x6d, 0x60, 0x6b, 0xc9, 0x12, 0xdf,
	0xa4, 0x03, 0xb5, 0x7e, 0xe8, 0xfb, 0xcc, 0x1d, 0x5e, 0xb4, 0x8b, 0xc2, 0x2a, 0x2e, 0x9b, 0x3f,
	0x01, 0xf2, 0x26, 0xb0, 0x83, 0x70, 0xde, 0xf7, 0x46, 0xcc, 0x62, 0xf3, 0x99, 0xe7, 0xce, 0x19,
	0xd9, 0x87, 0x8a, 0xac, 0x15, 0xb3, 0x14, 0x2d, 0x55, 0x32, 0x7f, 0x0b, 0x7b, 0x2f, 0x58, 0xf0,
	0x1b, 0x7b, 0x32, 0x61, 0xc1, 0x4b, 0xf7, 0xd4, 0x8b, 0xbc, 0xfb, 0x04, 0xb6, 0x86, 0xca, 0x8f,
	0x81, 0x9b, 0x72, 0x6f, 0x98, 0x76, 0x0f, 0x5d, 0x19, 0x46, 0xae, 0x18, 0xd2, 0x95, 0xa8, 0x6c,
	0xf6, 0xe1, 0x5a, 0x66, 0xf0, 0xc4, 0x9b, 0x79, 0xca, 0x1b, 0x59, 0xe2, 0x6b, 0xc5, 0xe8, 0xd8,
	0x6a, 0x20, 0xf1, 0x6d, 0xfe, 0xc7, 0x80, 0x76, 0xdf, 0x67, 0x18, 0xb4, 0xb7, 0xbe, 0xed, 0xce,
	0xed, 0x61, 0xe0, 0x78, 0x31, 0x88, 0xb7, 0xa1, 0x62, 0x4f, 0xbd, 0xd0, 0x0d, 0xc4, 0x40, 0xa5,
	0x5e, 0xf5, 0x7d, 0xaf, 0xd4, 0x35, 0xee, 0x6f, 0x58, 0xaa, 0x9a, 0x3c, 0x82, 0x56, 0xe4, 0xce,
	0x60, 0x88, 0x80, 0xc8, 0xa1, 0x7b, 0xb5, 0xf7, 0xbd, 0xb2, 0x5f, 0xfc, 0x53, 0xa1, 0x68, 0x35,
	0xa3, 0x66, 0x0e, 0x17, 0x79, 0x0a, 0x24, 0x48, 0x66, 0x19, 0x4c, 0x59, 0x70, 0xe6, 0x8d, 0x24,
	0xc4, 0x62, 0x6c, 0xdf, 0xd8, 0xde, 0xb0, 0x76, 0xb4, 0x2e, 0xaf, 0x45, 0x0f, 0xf2, 0x23, 0xa8,
	0x87, 0x73, 0x84, 0x2a, 0x0c, 0x9d, 0x51, 0xbb, 0xa4, 0x4d, 0xf1, 0x7d, 0xa1, 0x60, 0xd5, 0x78,
	0xd3, 0x31, 0xb6, 0x90, 0xc7, 0x8b, 0xa8, 0x96, 0xd3, 0x63, 0x67, 0xe1, 0x6d, 0x43, 0x15, 0x8d,
	0xcf, 0x9d, 0x21, 0x6b, 0x57, 0x04, 0x28, 0x51, 0x91, 0x03, 0x8f, 0xee, 0xd9, 0x02, 0xaf, 0xaa,
	0x04, 0x3e, 0x2a, 0xe3, 0xaa, 0x53, 0xcb, 0x18, 0x61, 0xbd, 0x33, 0x69, 0xd7, 0x44, 0x2f, 0xdd,
	0xfb, 0x43, 0xd1, 0x40, 0xf6, 0xa0, 0x8c, 0xc9, 0x82, 0x20, 0xd6, 0x45, 0x0f, 0x59, 0x30, 0x0f,
	0xe0, 0x46, 0x0e, 0xee, 0x2a, 0x82, 0x18, 0x29, 0x01, 0xa7, 0x8c, 0x9f, 0xf8, 0x36, 0x1f, 0x00,
	0x60, 0xb8, 0xa3, 0xd0, 0xdc, 0x82, 0x92, 0x40, 0xa3, 0x90, 0x41, 0x43, 0xd4, 0x9a, 0x4f, 0xa0,
	0x21, 0xfa, 0x26, 0xc3, 0x89, 0x85, 0x14, 0x92, 0xc0, 0xc7, 0x53, 0x18, 0xda, 0x14, 0xcf, 0xe1,
	0x16, 0x9a, 0x69, 0x0e, 0x7d, 0xe9, 0x20, 0x5c, 0xfe, 0x85, 0x96, 0x54, 0xc3, 0xdc, 0xa4, 0x4a,
	0xd7, 0x9a, 0x7f, 0x2d, 0xc0, 0x8d, 0xe3, 0x19, 0x57, 0x82, 0x37, 0xe1, 0xc9, 0x7c, 0xe8, 0x3b,
	0x33, 0x9d, 0x55, 0x97, 0xba, 0xce, 0x81, 0x1f, 0x85, 0xbe, 0xcd, 0x0d, 0x84, 0x6f, 0x2d, 0x2b,
	0x2e, 0x6b, 0xc4, 0x2e, 0x8a, 0x96, 0x88, 0xd8, 0x9f, 0x43, 0x63, 0x78, 0x66, 0xfb, 0x63, 0x36,
	0xe0, 0x73, 0x0a, 0x86, 0x34, 0xba, 0x1d, 0x2a, 0xe5, 0x82, 0x46, 0x72, 0x41, 0xdf, 0x46, 0xf2,
	0x63, 0x81, 0xec, 0x7e, 0x88, 0xbd, 0xcd, 0xc7, 0xd0, 0xc9, 0xf3, 0x35, 0x27, 0x12, 0x25, 0x05,
	0xd3, 0x3f, 0x0a, 0xb0, 0x2d, 0x63, 0x87, 0x26, 0xd1, 0xaa, 0x1e, 0x42, 0x73, 0x66, 0x0f, 0xdf,
	0x61, 0x70, 0x07, 0xb9, 0xab, 0x6b, 0xa8, 0xd6, 0x65, 0x4c, 0x35, 0x2e, 0x67, 0xea, 0xdd, 0x84,
	0xa9, 0x99, 0x7c, 0x89, 0x29, 0x7b, 0x4f, 0x43, 0x8e, 0x43, 0xd0, 0x12, 0x7d, 0x1e, 0x18, 0x77,
	0x36, 0x34, 0x08, 0x3f, 0x02, 0x40, 0x3c, 0xa6, 0x9e, 0x4c, 0x57, 0x91, 0x1e, 0x56, 0x5d, 0xd4,
	0xf0, 0x0c, 0x35, 0x7f, 0x07, 0xd0, 0xb7, 0x87, 0x67, 0xec, 0xb9, 0xc3, 0x26, 0xb9, 0x6e, 0x16,
	0x56, 0x4e, 0x28, 0x23, 0x9d, 0x50, 0x77, 0x33, 0xf8, 0x48, 0x61, 0xd5, 0x51, 0x31, 0xc7, 0xb0,
	0x8d, 0xf4, 0x93, 0x59, 0x13, 0xc1, 0xfa, 0x71, 0x3e, 0x59, 0xbe, 0xdc, 0x50, 0x74, 0xb9, 0x07,
	0xe5, 0x53, 0xee, 0xab, 0x98, 0xae, 0xd1, 0x6d, 0xd0, 0xc4, 0x7d, 0xec, 0x23, 0xdb, 0x7a, 0x9b,
	0x50, 0xf5, 0xd5, 0x78, 0xc5, 0xff, 0xf6, 0x0a, 0xa6, 0x07, 0xd7, 0x71, 0x22, 0x3d, 0xde, 0xf3,
	0x0f, 0x0a, 0xe3, 0x27, 0x4b, 0xc2, 0xb8, 0x90, 0x10, 0x3d, 0x68, 0x2f, 0x4e, 0xb8, 0x66, 0x72,
	0xfe, 0xad, 0x04, 0x3b, 0x1a, 0x3c, 0xca, 0xfa, 0xe7, 0x00, 0x48, 0x69, 0x3f, 0x90, 0xcc, 0x2f,
	0x5c, 0xc9, 0xfc, 0xba, 0xe8, 0xcd, 0x89, 0x4f, 0x9e, 0x40, 0x8d, 0xb9, 0x23, 0x69, 0x68, 0x5c,
	0x69, 0x58, 0xc5, 0xbe, 0xc2, 0x8c, 0x33, 0x48, 0x21, 0x14, 0x87, 0xb1, 0xae, 0x6a, 0x5e, 0x8e,
	0xb8, 0xeb, 0xc1, 0xc5, 0x4c, 0x26, 0x61, 0xcb, 0x12, 0xdf, 0xa9, 0x9c, 0x2e, 0x67, 0x72, 0xfa,
	0x1e, 0xb4, 0x1c, 0x37, 0x40, 0x92, 0xd8, 0x93, 0x01, 0x3f, 0x1f, 0x08, 0x21, 0x6e, 0x59, 0xcd,
	0xa8, 0x92, 0x7b, 0xc0, 0x25, 0xf4, 0xdb, 0xd0, 0x53, 0x52, 0xdc, 0xb2, 0x64, 0x81, 0xd7, 0xce,
	0x7c, 0x4e, 0xb5, 0x9a, 0x48, 0x4e, 0x59, 0xc8, 0x0b, 0x4a, 0x3d, 0x77, 0x6f, 0x4d, 0xd4, 0x04,
	0x52, 0x6a, 0x82, 0x5b, 0xfc, 0x99, 0x7d, 0xce, 0x06, 0x81, 0xef, 0xa0, 0x4f, 0x6a, 0x65, 0xed,
	0x06, 0xf6, 0xa9, 0x59, 0xdb, 0xbc, 0xe5, 0x2d, 0x6f, 0x38, 0x92, 0xf5, 0xb8, 0x37, 0x6d, 0xca,
	0x8e, 0xf1, 0x0a, 0x9b, 0x62, 0xb6, 0x96, 0xa8, 0x3d, 0x8c, 0x96, 0x79, 0x1b, 0x1a, 0x72, 0xf8,
	0x81, 0x6b, 0xe3, 0x22, 0x5b, 0xa2, 0x0f, 0xc8, 0xaa, 0xaf, 0xb1, 0x86, 0xe3, 0x26, 0x08, 0xb7,
	0x29, 0x69, 0x20, 0xc8, 0x9d, 0xd1, 0xb5, 0xad, 0xb5, 0x74, 0xad, 0x07, 0x9b, 0x48, 0x97, 0xaf,
	0x50, 0xc1, 0x23, 0x6e, 0xaf, 0x9d, 0xce, 0xe6, 0xbf, 0x0c, 0x68, 0xca, 0x11, 0x7e, 0xa8, 0x74,
	0x8b, 0x39, 0x50, 0xd2, 0x39, 0xa0, 0xc9, 0x50, 0x39, 0x2d, 0x43, 0x49, 0xd0, 0x2b, 0xa9, 0xa0,
	0x7f, 0x0c, 0x5a, 0x30, 0xd4, 0x8e, 0xaf, 0x87, 0x67, 0x81, 0xa6, 0xb5, 0x1c, 0x9a, 0x66, 0xe2,
	0x55, 0x5f, 0x2b, 0x5e, 0x3f, 0x85, 0xad, 0x38, 0x5e, 0x0a, 0xed, 0xbb, 0xb1, 0x34, 0x14, 0x71,
	0xa0, 0x16, 0xd5, 0x1b, 0xd5, 0xf9, 0xed, 0x1b, 0x20, 0x68, 0xa5, 0xc8, 0x38, 0x5f, 0x6d, 0x8b,
	0x4d, 0xef, 0x01, 0x46, 0x76, 0x0f, 0xf8, 0xbd, 0x01, 0xf5, 0x23, 0x5e, 0x12, 0xc4, 0x25, 0xfa,
	0x50, 0x6a, 0x00, 0x04, 0x3d, 0x70, 0x82, 0x49, 0x64, 0x2b, 0x0b, 0xe4, 0x0e, 0x34, 0x46, 0x2c,
	0x16, 0xb8, 0x48, 0xe0, 0xb5, 0xaa, 0x5c, 0x6d, 0xc0, 0xb1, 0x10, 0xbe, 0x50, 0x06, 0x0a, 0x03,
	0x28, 0x0a, 0x19, 0x9e, 0x55, 0x3e, 0x94, 0x67, 0xd5, 0xd5, 0x79, 0x86, 0xbe, 0xf1, 0x03, 0x9e,
	0x3a, 0xc6, 0x89, 0x6f, 0xf3, 0xcf, 0x25, 0xd8, 0x4d, 0xa1, 0xfb, 0x7f, 0xcb, 0x82, 0x98, 0xe6,
	0x45, 0x9d, 0xe6, 0x48, 0x66, 0x7e, 0x4e, 0x3b, 0x97, 0x88, 0xd6, 0x2c, 0x55, 0x8a, 0x71, 0x2e,
	0x6b, 0x38, 0xe7, 0xc8, 0x62, 0x25, 0x57, 0x16, 0x23, 0x20, 0xaa, 0x09, 0x10, 0x4b, 0x24, 0xb1,
	0xb6, 0xb2, 0x24, 0xd6, 0xf3, 0x24, 0x71, 0x21, 0xa5, 0xe0, 0x32, 0xe5, 0x6f, 0xe8, 0xca, 0xaf,
	0x6f, 0x28, 0xcd, 0xcc, 0x86, 0x82, 0x07, 0x0d, 0x95, 0xec, 0xba, 0xd4, 0x36, 0x54, 0x9d, 0x48,
	0x66, 0xfd, 0x56, 0xb5, 0x99, 0xbe, 0x55, 0x91, 0xfb, 0x20, 0x53, 0x41, 0x8c, 0x2d, 0x15, 0x17,
	0x68, 0x9c, 0x0e, 0x56, 0xd2, 0x68, 0xde, 0x85, 0xc6, 0xf1, 0xf1, 0xcb, 0xc3, 0x28, 0xe7, 0x72,
	0x12, 0xc5, 0xfc, 0x14, 0xb6, 0x5e, 0xcb, 0xbb, 0x72, 0xcc, 0x9d, 0x58, 0x68, 0xfa, 0xc9, 0x01,
	0x5f, 0xab, 0x31, 0xff, 0x60, 0xc0, 0xb5, 0x23, 0x79, 0xcf, 0x7e, 0x81, 0x91, 0xff, 0xce, 0xbe,
	0xd0, 0x26, 0x10, 0x0b, 0x52, 0x13, 0xf0, 0xef, 0x6c, 0xce, 0x19, 0x8b, 0x39, 0x87, 0xf3, 0xc9,
	0x7b, 0x96, 0x10, 0x36, 0x99, 0x94, 0x5a, 0x4d, 0xd2, 0xfe, 0x36, 0xc9, 0x4c, 0xad, 0x06, 0xa5,
	0xa4, 0x2e, 0x4b, 0xc7, 0xd6, 0x57, 0xd1, 0x79, 0x31, 0xae, 0xd0, 0x18, 0x58, 0x49, 0x31, 0xf0,
	0x26, 0xd4, 0xcf, 0x82, 0x60, 0x36, 0x10, 0x34, 0xe4, 0x4c, 0x2a, 0x5b, 0x35, 0x5e, 0x21, 0x86,
	0x7c, 0x80, 0x64, 0xb6, 0x7d, 0x7b, 0x8a, 0x04, 0xe2, 0xba, 0xb6, 0x47, 0xd3, 0xeb, 0x3d, 0xe2,
	0x6d, 0x96, 0xec, 0x62, 0xfe, 0xdb, 0x80, 0xfd, 0x2c, 0x1c, 0x0a, 0xc9, 0x4d, 0x30, 0x14, 0xdc,
	0x45, 0xcb, 0x90, 0xb2, 0x36, 0x14, 0xa7, 0xf2, 0xd1, 0xc0, 0x0e, 0x22, 0x59, 0x53, 0x35, 0xcf,
	0x02, 0xde, 0x1c, 0x8a, 0x73, 0xbe, 0x68, 0x56, 0x1b, 0x89, 0xaa, 0x79, 0x96, 0x84, 0xaf, 0xa4,
	0xe9, 0x5c, 0x84, 0x78, 0x79, 0x39, 0xe2, 0x95, 0xab, 0x10, 0xaf, 0x5e, 0x81, 0x78, 0x4d, 0x6f,
	0x5f, 0x44, 0xbc, 0xbe, 0x1c, 0x71, 0x58, 0x8e, 0x78, 0x43, 0x92, 0x7a, 0x11, 0xf1, 0xe6, 0xd5,
	0x88, 0x7f, 0x03, 0xbb, 0x39, 0xad, 0x64, 0x1b, 0x8a, 0xef, 0xd8, 0x85, 0x22, 0x1f, 0xff, 0x4c,
	0x94, 0x5b, 0xed, 0x02, 0x52, 0xb9, 0x23, 0xed, 0x91, 0x00, 0x8b, 0x6f, 0xf3, 0x15, 0xdc, 0xe4,
	0x5b, 0x57, 0x7a, 0xd8, 0x44, 0x4e, 0x1f, 0xa6, 0xb6, 0xb9, 0xeb, 0x34, 0x3f, 0xde, 0x72, 0xc3,
	0xeb, 0xfe, 0xa5, 0xc4, 0x5f, 0x6c, 0x7c, 0x46, 0x3e, 0x85, 0x26, 0x6a, 0x73, 0xdf, 0x73, 0x4f,
	0x9d, 0xf1, 0xb3, 0xa3, 0x97, 0x64, 0x0b, 0x75, 0x94, 0xf2, 0xc7, 0x22, 0x95, 0x2f, 0x9d, 0xed,
	0xa4, 0x42, 0x4d, 0x44, 0xa1, 0xde, 0x17, 0x1b, 0xee, 0x8a, 0xfd, 0x1f, 0xf3, 0x37, 0xa5, 0xd0,
	0x0d, 0x9e, 0xb3, 0x55, 0x2d, 0x1e, 0x41, 0xcd, 0x62, 0x2e, 0xfb, 0x6e, 0xc5, 0xee, 0xbf, 0x14,
	0xf7, 0x82, 0xc5, 0x0b, 0xf7, 0x8a, 0xe6, 0x9f, 0xc3, 0x3e, 0x3f, 0x32, 0xd8, 0xf3, 0xd4, 0xd5,
	0x62, 0x3d, 0x63, 0xe7, 0x83, 0x8c, 0x9f, 0xc2, 0x8e, 0x8a, 0xd2, 0x1b, 0x16, 0x04, 0x8e, 0xbb,
	0x6a, 0x04, 0x30, 0x68, 0xaf, 0xbc, 0x13, 0x2b, 0x74, 0x5d, 0xe6, 0xaf, 0x68, 0x82, 0xe7, 0x22,
	0xf9, 0x9a, 0xb6, 0x8e, 0x55, 0x17, 0x65, 0x14, 0x22, 0x0f, 0xfd, 0x73, 0x04, 0x7a, 0xe7, 0xd9,
	0x68, 0x94, 0x26, 0x16, 0xd9, 0xa7, 0xb9, 0x42, 0x8b, 0xa3, 0x65, 0x45, 0xfb, 0xd7, 0xb0, 0x9b,
	0x43, 0x60, 0x1c, 0x20, 0xbb, 0x75, 0xff, 0x8a, 0xbf, 0x48, 0x76, 0x6e, 0xd1, 0xcb, 0xe8, 0xfe,
	0x14, 0xf6, 0x0e, 0xd9, 0x84, 0x05, 0x2c, 0xe3, 0x4e, 0x93, 0x6a, 0xdb, 0x49, 0x8e, 0x13, 0xbf,
	0x10, 0xf7, 0xbf, 0x4b, 0x8d, 0x96, 0xe5, 0x4e, 0xf7, 0x8f, 0x25, 0x28, 0x1e, 0xbd, 0x1b, 0x93,
	0x2e, 0xb4, 0x04, 0x0e, 0x62, 0xa3, 0x5e, 0x3d, 0x00, 0x72, 0x39, 0xf2, 0x14, 0xb4, 0xa2, 0xd5,
	0x13, 0xd8, 0x96, 0xcf, 0x2a, 0xeb, 0x4d, 0x86, 0x66, 0x11, 0x38, 0xeb, 0x98, 0xe1, 0xba, 0x92,
	0x83, 0xda, 0x8a, 0x36, 0x07, 0x00, 0x16, 0x1b, 0xf3, 0xbb, 0xf8, 0xea, 0xe4, 0x45, 0xf0, 0xa4,
	0xcd, 0xea, 0xd8, 0x49, 0x14, 0xd6, 0xb5, 0x92, 0x20, 0xac, 0x65, 0x25, 0x05, 0x71, 0x1d, 0x93,
	0xee, 0x0b, 0xa8, 0x20, 0x2b, 0x64, 0x82, 0x6c, 0x27, 0x00, 0xf6, 0x2e, 0x38, 0xa9, 0xc8, 0x2e,
	0x5d, 0xbc, 0x5a, 0x74, 0xf6, 0x68, 0xce, 0x89, 0xb8, 0xfb, 0x4f, 0xbc, 0x28, 0xea, 0x32, 0x82,
	0xea, 0x42, 0xe2, 0x27, 0xb2, 0xa4, 0x76, 0x87, 0x66, 0xdf, 0xcd, 0x3a, 0x84, 0x2e, 0x3e, 0x6a,
	0x7c, 0x21, 0x5e, 0xb6, 0x75, 0x4b, 0xf5, 0x94, 0xba, 0x43, 0xb3, 0x0f, 0x44, 0xb9, 0xf6, 0x3f,
	0x13, 0xc7, 0xf6, 0xac, 0xb4, 0x21, 0x20, 0xe9, 0x0b, 0x31, 0x02, 0x92, 0xbd, 0x71, 0xbd, 0x92,
	0x96, 0x19, 0x45, 0x25, 0x6d, 0xba, 0xe4, 0xbd, 0xa8, 0x73, 0x83, 0x2e, 0x7d, 0xd8, 0x79, 0x0d,
	0x64, 0xf1, 0x61, 0x91, 0x74, 0xe8, 0xd2, 0x97, 0xd1, 0xce, 0x4d, 0xba, 0xfc, 0x25, 0xb2, 0xfb,
	0xf7, 0x02, 0x34, 0xb4, 0x9d, 0x02, 0x35, 0x89, 0x2c, 0x3c, 0x20, 0xcf, 0xc9, 0x0d, 0xba, 0xec,
	0x35, 0xbf, 0xd3, 0xa1, 0xcb, 0x1f, 0x9c, 0x1f, 0x8a, 0xc7, 0x02, 0x7d, 0xf8, 0x06, 0x4d, 0x5e,
	0x9b, 0x3b, 0x4d, 0xaa, 0x3f, 0x27, 0x1f, 0x8a, 0xf0, 0x2c, 0xee, 0x5a, 0xe4, 0x23, 0x7a, 0xd9,
	0xf3, 0x71, 0x7a, 0x94, 0xee, 0xf7, 0x05, 0xa8, 0xcb, 0x9f, 0x17, 0x9c, 0x7f, 0x14, 0xaa, 0x98,
	0x5b, 0xe2, 0xf7, 0x4b, 0x93, 0x6a, 0x3f, 0x72, 0x3a, 0xbb, 0x74, 0xf1, 0x7f, 0x8b, 0xb9, 0x41,
	0x3e, 0x13, 0x7c, 0x0b, 0x7c, 0x9c, 0x68, 0x75, 0xa3, 0x2f, 0x84, 0x4a, 0x24, 0x7f, 0x4c, 0xc8,
	0x35, 0x9a, 0xf7, 0x7b, 0xa6, 0xb3, 0x4f, 0x73, 0x7f, 0xac, 0x9c, 0x54, 0x84, 0xce, 0x7f, 0xf6,
	0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xcd, 0xbc, 0x91, 0x09, 0x1b, 0x00, 0x00,
}
