// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voice-call/message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/micro/go-micro/api/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CallingRequest struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	UrlMedia             string   `protobuf:"bytes,2,opt,name=urlMedia,proto3" json:"urlMedia,omitempty"`
	UrlCallback          string   `protobuf:"bytes,3,opt,name=urlCallback,proto3" json:"urlCallback,omitempty"`
	NotificationID       string   `protobuf:"bytes,4,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	CallID               string   `protobuf:"bytes,5,opt,name=callID,proto3" json:"callID,omitempty"`
	CallbackType         string   `protobuf:"bytes,6,opt,name=callbackType,proto3" json:"callbackType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallingRequest) Reset()         { *m = CallingRequest{} }
func (m *CallingRequest) String() string { return proto.CompactTextString(m) }
func (*CallingRequest) ProtoMessage()    {}
func (*CallingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d77be9c6119632, []int{0}
}

func (m *CallingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallingRequest.Unmarshal(m, b)
}
func (m *CallingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallingRequest.Marshal(b, m, deterministic)
}
func (m *CallingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallingRequest.Merge(m, src)
}
func (m *CallingRequest) XXX_Size() int {
	return xxx_messageInfo_CallingRequest.Size(m)
}
func (m *CallingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallingRequest proto.InternalMessageInfo

func (m *CallingRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *CallingRequest) GetUrlMedia() string {
	if m != nil {
		return m.UrlMedia
	}
	return ""
}

func (m *CallingRequest) GetUrlCallback() string {
	if m != nil {
		return m.UrlCallback
	}
	return ""
}

func (m *CallingRequest) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *CallingRequest) GetCallID() string {
	if m != nil {
		return m.CallID
	}
	return ""
}

func (m *CallingRequest) GetCallbackType() string {
	if m != nil {
		return m.CallbackType
	}
	return ""
}

type MessageRequest struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	UrlCallback          string   `protobuf:"bytes,3,opt,name=urlCallback,proto3" json:"urlCallback,omitempty"`
	NotificationID       string   `protobuf:"bytes,4,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	MessageID            string   `protobuf:"bytes,5,opt,name=messageID,proto3" json:"messageID,omitempty"`
	CallbackType         string   `protobuf:"bytes,6,opt,name=callbackType,proto3" json:"callbackType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d77be9c6119632, []int{1}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MessageRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *MessageRequest) GetUrlCallback() string {
	if m != nil {
		return m.UrlCallback
	}
	return ""
}

func (m *MessageRequest) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *MessageRequest) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *MessageRequest) GetCallbackType() string {
	if m != nil {
		return m.CallbackType
	}
	return ""
}

type GetCallRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCallRequest) Reset()         { *m = GetCallRequest{} }
func (m *GetCallRequest) String() string { return proto.CompactTextString(m) }
func (*GetCallRequest) ProtoMessage()    {}
func (*GetCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d77be9c6119632, []int{2}
}

func (m *GetCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCallRequest.Unmarshal(m, b)
}
func (m *GetCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCallRequest.Marshal(b, m, deterministic)
}
func (m *GetCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCallRequest.Merge(m, src)
}
func (m *GetCallRequest) XXX_Size() int {
	return xxx_messageInfo_GetCallRequest.Size(m)
}
func (m *GetCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCallRequest proto.InternalMessageInfo

func (m *GetCallRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type GetCallResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	From                 string   `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	UrlMedia             string   `protobuf:"bytes,6,opt,name=urlMedia,proto3" json:"urlMedia,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,7,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	NotificationID       string   `protobuf:"bytes,8,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	CallID               string   `protobuf:"bytes,9,opt,name=callID,proto3" json:"callID,omitempty"`
	Sid                  string   `protobuf:"bytes,10,opt,name=sid,proto3" json:"sid,omitempty"`
	Error                string   `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCallResponse) Reset()         { *m = GetCallResponse{} }
func (m *GetCallResponse) String() string { return proto.CompactTextString(m) }
func (*GetCallResponse) ProtoMessage()    {}
func (*GetCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d77be9c6119632, []int{3}
}

func (m *GetCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCallResponse.Unmarshal(m, b)
}
func (m *GetCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCallResponse.Marshal(b, m, deterministic)
}
func (m *GetCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCallResponse.Merge(m, src)
}
func (m *GetCallResponse) XXX_Size() int {
	return xxx_messageInfo_GetCallResponse.Size(m)
}
func (m *GetCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCallResponse proto.InternalMessageInfo

func (m *GetCallResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetCallResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetCallResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetCallResponse) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetCallResponse) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *GetCallResponse) GetUrlMedia() string {
	if m != nil {
		return m.UrlMedia
	}
	return ""
}

func (m *GetCallResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetCallResponse) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *GetCallResponse) GetCallID() string {
	if m != nil {
		return m.CallID
	}
	return ""
}

func (m *GetCallResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *GetCallResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetMessageResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	From                 string   `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Body                 string   `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,7,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	NotificationID       string   `protobuf:"bytes,8,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	MessageID            string   `protobuf:"bytes,9,opt,name=messageID,proto3" json:"messageID,omitempty"`
	Sid                  string   `protobuf:"bytes,10,opt,name=sid,proto3" json:"sid,omitempty"`
	Error                string   `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageResponse) Reset()         { *m = GetMessageResponse{} }
func (m *GetMessageResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessageResponse) ProtoMessage()    {}
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d77be9c6119632, []int{4}
}

func (m *GetMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageResponse.Unmarshal(m, b)
}
func (m *GetMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageResponse.Marshal(b, m, deterministic)
}
func (m *GetMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageResponse.Merge(m, src)
}
func (m *GetMessageResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessageResponse.Size(m)
}
func (m *GetMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageResponse proto.InternalMessageInfo

func (m *GetMessageResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetMessageResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetMessageResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetMessageResponse) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetMessageResponse) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *GetMessageResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *GetMessageResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetMessageResponse) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *GetMessageResponse) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *GetMessageResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *GetMessageResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CallingResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	DateCreated          string   `protobuf:"bytes,5,opt,name=dateCreated,proto3" json:"dateCreated,omitempty"`
	DateUpdated          string   `protobuf:"bytes,6,opt,name=dateUpdated,proto3" json:"dateUpdated,omitempty"`
	StartTime            string   `protobuf:"bytes,7,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,8,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Duration             string   `protobuf:"bytes,9,opt,name=duration,proto3" json:"duration,omitempty"`
	ForwardedFrom        string   `protobuf:"bytes,10,opt,name=forwardedFrom,proto3" json:"forwardedFrom,omitempty"`
	Price                float32  `protobuf:"fixed32,11,opt,name=price,proto3" json:"price,omitempty"`
	PriceUnit            string   `protobuf:"bytes,12,opt,name=priceUnit,proto3" json:"priceUnit,omitempty"`
	Type                 string   `protobuf:"bytes,13,opt,name=type,proto3" json:"type,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,14,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Error                string   `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	NotificationID       string   `protobuf:"bytes,16,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	CallID               string   `protobuf:"bytes,17,opt,name=callID,proto3" json:"callID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallingResponse) Reset()         { *m = CallingResponse{} }
func (m *CallingResponse) String() string { return proto.CompactTextString(m) }
func (*CallingResponse) ProtoMessage()    {}
func (*CallingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d77be9c6119632, []int{5}
}

func (m *CallingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallingResponse.Unmarshal(m, b)
}
func (m *CallingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallingResponse.Marshal(b, m, deterministic)
}
func (m *CallingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallingResponse.Merge(m, src)
}
func (m *CallingResponse) XXX_Size() int {
	return xxx_messageInfo_CallingResponse.Size(m)
}
func (m *CallingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallingResponse proto.InternalMessageInfo

func (m *CallingResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *CallingResponse) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *CallingResponse) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *CallingResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CallingResponse) GetDateCreated() string {
	if m != nil {
		return m.DateCreated
	}
	return ""
}

func (m *CallingResponse) GetDateUpdated() string {
	if m != nil {
		return m.DateUpdated
	}
	return ""
}

func (m *CallingResponse) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *CallingResponse) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *CallingResponse) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *CallingResponse) GetForwardedFrom() string {
	if m != nil {
		return m.ForwardedFrom
	}
	return ""
}

func (m *CallingResponse) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CallingResponse) GetPriceUnit() string {
	if m != nil {
		return m.PriceUnit
	}
	return ""
}

func (m *CallingResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CallingResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *CallingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CallingResponse) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *CallingResponse) GetCallID() string {
	if m != nil {
		return m.CallID
	}
	return ""
}

type MessageResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	DateCreated          string   `protobuf:"bytes,5,opt,name=dateCreated,proto3" json:"dateCreated,omitempty"`
	DateSent             string   `protobuf:"bytes,6,opt,name=dateSent,proto3" json:"dateSent,omitempty"`
	DateUpdated          string   `protobuf:"bytes,7,opt,name=dateUpdated,proto3" json:"dateUpdated,omitempty"`
	Segments             string   `protobuf:"bytes,8,opt,name=segments,proto3" json:"segments,omitempty"`
	Price                float32  `protobuf:"fixed32,9,opt,name=price,proto3" json:"price,omitempty"`
	PriceUnit            string   `protobuf:"bytes,10,opt,name=priceUnit,proto3" json:"priceUnit,omitempty"`
	Type                 string   `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,12,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Body                 string   `protobuf:"bytes,13,opt,name=body,proto3" json:"body,omitempty"`
	Error                string   `protobuf:"bytes,14,opt,name=error,proto3" json:"error,omitempty"`
	NotificationID       string   `protobuf:"bytes,15,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	MessageID            string   `protobuf:"bytes,16,opt,name=messageID,proto3" json:"messageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d77be9c6119632, []int{6}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *MessageResponse) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MessageResponse) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MessageResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MessageResponse) GetDateCreated() string {
	if m != nil {
		return m.DateCreated
	}
	return ""
}

func (m *MessageResponse) GetDateSent() string {
	if m != nil {
		return m.DateSent
	}
	return ""
}

func (m *MessageResponse) GetDateUpdated() string {
	if m != nil {
		return m.DateUpdated
	}
	return ""
}

func (m *MessageResponse) GetSegments() string {
	if m != nil {
		return m.Segments
	}
	return ""
}

func (m *MessageResponse) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MessageResponse) GetPriceUnit() string {
	if m != nil {
		return m.PriceUnit
	}
	return ""
}

func (m *MessageResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MessageResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *MessageResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *MessageResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *MessageResponse) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *MessageResponse) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func init() {
	proto.RegisterType((*CallingRequest)(nil), "CallingRequest")
	proto.RegisterType((*MessageRequest)(nil), "MessageRequest")
	proto.RegisterType((*GetCallRequest)(nil), "GetCallRequest")
	proto.RegisterType((*GetCallResponse)(nil), "GetCallResponse")
	proto.RegisterType((*GetMessageResponse)(nil), "GetMessageResponse")
	proto.RegisterType((*CallingResponse)(nil), "CallingResponse")
	proto.RegisterType((*MessageResponse)(nil), "MessageResponse")
}

func init() { proto.RegisterFile("voice-call/message.proto", fileDescriptor_45d77be9c6119632) }

var fileDescriptor_45d77be9c6119632 = []byte{
	// 723 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x56, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xa5, 0x4e, 0x93, 0x36, 0x93, 0xd4, 0x0e, 0x0b, 0x42, 0x56, 0xc5, 0xa1, 0xb2, 0x10, 0xe2,
	0x52, 0x07, 0xb5, 0x27, 0x8e, 0xa5, 0x08, 0xd4, 0x43, 0x25, 0x94, 0xb6, 0x1f, 0xe0, 0xd8, 0xdb,
	0xb0, 0xa2, 0xf1, 0x86, 0xf5, 0xa6, 0xa8, 0x9f, 0x04, 0x3f, 0xc0, 0x15, 0x71, 0xe2, 0x2f, 0xf8,
	0x15, 0x76, 0x76, 0xd7, 0x1b, 0xdb, 0x49, 0xda, 0x1e, 0x2a, 0xb8, 0xcd, 0xcc, 0xce, 0xac, 0xf7,
	0xbd, 0x37, 0xb3, 0x6b, 0x08, 0xaf, 0x39, 0x4b, 0xe9, 0x7e, 0x9a, 0x5c, 0x5d, 0x0d, 0xa7, 0xb4,
	0x28, 0x92, 0x09, 0x8d, 0x67, 0x82, 0x4b, 0xbe, 0xbb, 0x3f, 0x61, 0xf2, 0xd3, 0x7c, 0x1c, 0xa7,
	0x7c, 0x3a, 0x9c, 0xb2, 0x54, 0xf0, 0xe1, 0x84, 0xef, 0x1b, 0x23, 0x99, 0xb1, 0xa1, 0x4e, 0x42,
	0xcb, 0xa4, 0x47, 0xbf, 0x36, 0xc0, 0x3f, 0x56, 0xbb, 0xb0, 0x7c, 0x32, 0xa2, 0x5f, 0xe6, 0xb4,
	0x90, 0xc4, 0x07, 0x4f, 0xf2, 0x70, 0x63, 0x6f, 0xe3, 0x55, 0x77, 0xa4, 0x2c, 0xb2, 0x0b, 0xdb,
	0x73, 0x71, 0x75, 0x4a, 0x33, 0x96, 0x84, 0x9e, 0x8e, 0x3a, 0x9f, 0xec, 0x41, 0x4f, 0xd9, 0xb8,
	0xc1, 0x38, 0x49, 0x3f, 0x87, 0x2d, 0xbd, 0x5c, 0x0d, 0x91, 0x97, 0xe0, 0xe7, 0x5c, 0xb2, 0x4b,
	0x96, 0x26, 0x92, 0xf1, 0xfc, 0xe4, 0x5d, 0xb8, 0xa9, 0x93, 0x1a, 0x51, 0xf2, 0x0c, 0x3a, 0x88,
	0x46, 0xad, 0xb7, 0xf5, 0xba, 0xf5, 0x48, 0x04, 0xfd, 0xd4, 0xee, 0x75, 0x7e, 0x33, 0xa3, 0x61,
	0x47, 0xaf, 0xd6, 0x62, 0xd1, 0x4f, 0x05, 0xe2, 0xd4, 0xb0, 0xb0, 0x0e, 0x04, 0x81, 0xcd, 0x31,
	0xcf, 0x6e, 0x2c, 0x00, 0x6d, 0x3f, 0xe0, 0xe1, 0x9f, 0x43, 0xd7, 0xaa, 0xe0, 0xce, 0xbf, 0x08,
	0xdc, 0x0b, 0x42, 0x04, 0xfe, 0x07, 0x2a, 0xf1, 0xc3, 0x25, 0x82, 0x01, 0xb4, 0x0a, 0x96, 0x59,
	0x08, 0x68, 0x46, 0xdf, 0x3c, 0x08, 0x5c, 0x52, 0x31, 0xe3, 0x79, 0x41, 0x11, 0xa7, 0x4d, 0x6a,
	0x8f, 0x94, 0x85, 0x27, 0x49, 0x05, 0x4d, 0x24, 0xcd, 0x8e, 0xa4, 0x05, 0xbb, 0x08, 0xe0, 0xea,
	0x7c, 0x96, 0xd9, 0x55, 0x83, 0x77, 0x11, 0x40, 0x8e, 0x2e, 0x05, 0x9f, 0x5a, 0x8c, 0xda, 0xb6,
	0x3c, 0xb6, 0x57, 0x36, 0x43, 0xa7, 0xd1, 0x0c, 0x0a, 0x27, 0x15, 0x82, 0x0b, 0x2b, 0x45, 0xb8,
	0x65, 0x70, 0x56, 0x63, 0x2b, 0x18, 0xdd, 0xbe, 0xa3, 0x1d, 0xba, 0xb5, 0x76, 0xb0, 0xac, 0x80,
	0x63, 0x85, 0x3c, 0x85, 0xb6, 0xfe, 0x42, 0xd8, 0xd3, 0x31, 0xe3, 0x44, 0xdf, 0x3d, 0x20, 0x8a,
	0x2b, 0xd7, 0x15, 0xff, 0x89, 0xae, 0xb2, 0xed, 0x3a, 0x95, 0xb6, 0x7b, 0x48, 0x9a, 0x6a, 0x8d,
	0xd7, 0x6d, 0x36, 0xde, 0x7d, 0xc9, 0xfa, 0xd3, 0x82, 0xc0, 0x5d, 0x02, 0x96, 0xa9, 0xa5, 0xf6,
	0x73, 0x78, 0xbd, 0x25, 0xbc, 0x2d, 0x87, 0x57, 0xc9, 0x56, 0xc8, 0x44, 0xce, 0x0b, 0xcb, 0x8a,
	0xf5, 0x70, 0xd4, 0x90, 0xb6, 0x63, 0x43, 0xad, 0x25, 0xa8, 0x1a, 0x2a, 0x33, 0x2e, 0x0c, 0xbd,
	0x96, 0xb0, 0x6a, 0x08, 0xb1, 0xaa, 0xdd, 0x84, 0x3c, 0x67, 0xd3, 0x92, 0xb4, 0x45, 0x80, 0x84,
	0xb0, 0x45, 0xf3, 0x4c, 0xaf, 0x19, 0xaa, 0x4a, 0x17, 0x5b, 0x36, 0x9b, 0x0b, 0xcd, 0x98, 0xa5,
	0xc8, 0xf9, 0xe4, 0x05, 0xec, 0x5c, 0x72, 0xf1, 0x35, 0x11, 0x19, 0xcd, 0xde, 0x23, 0x38, 0xc3,
	0x55, 0x3d, 0x88, 0xac, 0xcd, 0x84, 0xba, 0x6f, 0x35, 0x6b, 0xde, 0xc8, 0x38, 0x78, 0x1e, 0x6d,
	0x5c, 0xe4, 0x4c, 0x86, 0x7d, 0x73, 0x1e, 0x17, 0x40, 0xb6, 0x24, 0x0e, 0xfb, 0x8e, 0x61, 0x0b,
	0xed, 0x25, 0xe5, 0xfd, 0x15, 0xca, 0x3b, 0x85, 0x82, 0x8a, 0x42, 0x2b, 0xfa, 0x61, 0x70, 0xc7,
	0xd8, 0x3c, 0xae, 0x8e, 0x4d, 0xf4, 0x43, 0x29, 0xdc, 0x9c, 0x85, 0x7f, 0xad, 0x30, 0xea, 0xa0,
	0x8c, 0x33, 0x9a, 0xcb, 0xf2, 0xea, 0x28, 0xfd, 0xa6, 0xfa, 0x5b, 0xcb, 0xea, 0xab, 0xea, 0x82,
	0x4e, 0xa6, 0x2a, 0xb9, 0xb0, 0x02, 0x3b, 0x7f, 0xa1, 0x4f, 0x77, 0xad, 0x3e, 0xb0, 0x4e, 0x9f,
	0xde, 0x2d, 0xfa, 0xf4, 0x57, 0xe8, 0x53, 0x4e, 0xf4, 0x4e, 0x65, 0xa2, 0x9d, 0x66, 0xfe, 0xed,
	0x9a, 0x05, 0x77, 0xcf, 0xf0, 0xa0, 0x31, 0xc3, 0x07, 0xbf, 0x3d, 0x00, 0x3b, 0x9b, 0x67, 0xd7,
	0x29, 0x19, 0xc2, 0xb6, 0x22, 0x2c, 0xc3, 0x08, 0x09, 0xe2, 0xfa, 0xcb, 0xbd, 0x3b, 0x88, 0x1b,
	0x53, 0x1c, 0x3d, 0x22, 0x07, 0xd0, 0xc3, 0x82, 0xf2, 0xf8, 0x41, 0x5c, 0x7f, 0x28, 0x55, 0x4d,
	0xa3, 0x2f, 0x54, 0xcd, 0x21, 0xf4, 0xed, 0x3b, 0xf3, 0xf6, 0xe6, 0x4c, 0xf5, 0x45, 0x10, 0xd7,
	0xdf, 0x26, 0x55, 0xd4, 0x78, 0x87, 0x54, 0xd1, 0x1b, 0xfd, 0x38, 0xd9, 0xcd, 0xd6, 0xd4, 0x3d,
	0x89, 0x97, 0xef, 0x64, 0x55, 0xfa, 0xda, 0x9c, 0x11, 0x33, 0x8f, 0x3e, 0x9e, 0xa8, 0xb2, 0x09,
	0x8f, 0xf1, 0x17, 0x65, 0xf1, 0x39, 0x17, 0xb0, 0xbd, 0x7b, 0x08, 0x7e, 0x05, 0xd5, 0xfd, 0x8a,
	0xc6, 0x1d, 0xfd, 0xcb, 0x73, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x5c, 0xde, 0x1e, 0x3d,
	0x09, 0x00, 0x00,
}
