// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alert/message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/micro/go-micro/api/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AlertRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	CompareValue         string   `protobuf:"bytes,2,opt,name=compareValue,proto3" json:"compareValue,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlertRequest) Reset()         { *m = AlertRequest{} }
func (m *AlertRequest) String() string { return proto.CompactTextString(m) }
func (*AlertRequest) ProtoMessage()    {}
func (*AlertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa71fe8c44cc448, []int{0}
}

func (m *AlertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertRequest.Unmarshal(m, b)
}
func (m *AlertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertRequest.Marshal(b, m, deterministic)
}
func (m *AlertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertRequest.Merge(m, src)
}
func (m *AlertRequest) XXX_Size() int {
	return xxx_messageInfo_AlertRequest.Size(m)
}
func (m *AlertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlertRequest proto.InternalMessageInfo

func (m *AlertRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AlertRequest) GetCompareValue() string {
	if m != nil {
		return m.CompareValue
	}
	return ""
}

func (m *AlertRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AlertResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlertResponse) Reset()         { *m = AlertResponse{} }
func (m *AlertResponse) String() string { return proto.CompactTextString(m) }
func (*AlertResponse) ProtoMessage()    {}
func (*AlertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa71fe8c44cc448, []int{1}
}

func (m *AlertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertResponse.Unmarshal(m, b)
}
func (m *AlertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertResponse.Marshal(b, m, deterministic)
}
func (m *AlertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertResponse.Merge(m, src)
}
func (m *AlertResponse) XXX_Size() int {
	return xxx_messageInfo_AlertResponse.Size(m)
}
func (m *AlertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AlertResponse proto.InternalMessageInfo

func (m *AlertResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

//--
type AlertTypeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlertTypeRequest) Reset()         { *m = AlertTypeRequest{} }
func (m *AlertTypeRequest) String() string { return proto.CompactTextString(m) }
func (*AlertTypeRequest) ProtoMessage()    {}
func (*AlertTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa71fe8c44cc448, []int{2}
}

func (m *AlertTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertTypeRequest.Unmarshal(m, b)
}
func (m *AlertTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertTypeRequest.Marshal(b, m, deterministic)
}
func (m *AlertTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertTypeRequest.Merge(m, src)
}
func (m *AlertTypeRequest) XXX_Size() int {
	return xxx_messageInfo_AlertTypeRequest.Size(m)
}
func (m *AlertTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlertTypeRequest proto.InternalMessageInfo

type AlertTypeResponse struct {
	Items                []*AlertType `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AlertTypeResponse) Reset()         { *m = AlertTypeResponse{} }
func (m *AlertTypeResponse) String() string { return proto.CompactTextString(m) }
func (*AlertTypeResponse) ProtoMessage()    {}
func (*AlertTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa71fe8c44cc448, []int{3}
}

func (m *AlertTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertTypeResponse.Unmarshal(m, b)
}
func (m *AlertTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertTypeResponse.Marshal(b, m, deterministic)
}
func (m *AlertTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertTypeResponse.Merge(m, src)
}
func (m *AlertTypeResponse) XXX_Size() int {
	return xxx_messageInfo_AlertTypeResponse.Size(m)
}
func (m *AlertTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AlertTypeResponse proto.InternalMessageInfo

func (m *AlertTypeResponse) GetItems() []*AlertType {
	if m != nil {
		return m.Items
	}
	return nil
}

//--
type AlertType struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlertType) Reset()         { *m = AlertType{} }
func (m *AlertType) String() string { return proto.CompactTextString(m) }
func (*AlertType) ProtoMessage()    {}
func (*AlertType) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa71fe8c44cc448, []int{4}
}

func (m *AlertType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertType.Unmarshal(m, b)
}
func (m *AlertType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertType.Marshal(b, m, deterministic)
}
func (m *AlertType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertType.Merge(m, src)
}
func (m *AlertType) XXX_Size() int {
	return xxx_messageInfo_AlertType.Size(m)
}
func (m *AlertType) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertType.DiscardUnknown(m)
}

var xxx_messageInfo_AlertType proto.InternalMessageInfo

func (m *AlertType) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AlertType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*AlertRequest)(nil), "AlertRequest")
	proto.RegisterType((*AlertResponse)(nil), "AlertResponse")
	proto.RegisterType((*AlertTypeRequest)(nil), "AlertTypeRequest")
	proto.RegisterType((*AlertTypeResponse)(nil), "AlertTypeResponse")
	proto.RegisterType((*AlertType)(nil), "AlertType")
}

func init() {
	proto.RegisterFile("alert/message.proto", fileDescriptor_caa71fe8c44cc448)
}

var fileDescriptor_caa71fe8c44cc448 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0xfd, 0x01, 0x3f, 0x08, 0x8c, 0x80, 0x30, 0x1a, 0x43, 0x38, 0x91, 0xbd, 0xc8, 0x85, 0x6d,
	0x82, 0xc1, 0x78, 0x25, 0x1e, 0x8c, 0x37, 0x53, 0x8c, 0x27, 0x2f, 0x4b, 0x99, 0x94, 0xc6, 0x96,
	0xad, 0xdd, 0x2d, 0x89, 0x5f, 0xc5, 0x4f, 0x6b, 0x3b, 0x2d, 0xff, 0xf4, 0x62, 0xbc, 0xbd, 0x79,
	0x33, 0xef, 0xbd, 0xbe, 0xb6, 0x70, 0xa1, 0x42, 0x4a, 0xac, 0x13, 0x91, 0x31, 0xca, 0x27, 0x19,
	0x27, 0xda, 0xea, 0xe1, 0xc4, 0x0f, 0xec, 0x3a, 0x5d, 0x4a, 0x4f, 0x47, 0x4e, 0x14, 0x78, 0x89,
	0x76, 0x7c, 0x3d, 0x29, 0x80, 0x8a, 0x03, 0x87, 0x8f, 0x72, 0x54, 0x9c, 0x8b, 0x57, 0x68, 0xcf,
	0x73, 0x17, 0x97, 0xde, 0x53, 0x32, 0x16, 0x11, 0xfe, 0xdb, 0x8f, 0x98, 0x06, 0x95, 0x51, 0x65,
	0xdc, 0x72, 0x19, 0xa3, 0x80, 0x76, 0xe6, 0x16, 0xab, 0x84, 0x5e, 0x54, 0x98, 0xd2, 0xa0, 0xca,
	0xbb, 0x13, 0x0e, 0x2f, 0xa1, 0xbe, 0xe5, 0x65, 0x8d, 0x97, 0xc5, 0x20, 0xae, 0xa1, 0x53, 0xba,
	0x9b, 0x58, 0x6f, 0x0c, 0xe1, 0x15, 0x34, 0x12, 0x32, 0x69, 0x68, 0x39, 0xa0, 0xe9, 0x96, 0x93,
	0x40, 0xe8, 0xf1, 0xe1, 0x73, 0x96, 0x57, 0x3e, 0x8a, 0x98, 0x41, 0xff, 0x88, 0x2b, 0x0d, 0x46,
	0x50, 0x0f, 0x2c, 0x45, 0x26, 0xd3, 0xd7, 0xc6, 0x67, 0x53, 0x90, 0x87, 0x93, 0x62, 0x21, 0x1c,
	0x68, 0xed, 0x39, 0xec, 0x42, 0x35, 0x58, 0x71, 0x56, 0xdd, 0xcd, 0x50, 0x5e, 0x6f, 0xa3, 0xa2,
	0x5d, 0x05, 0xc6, 0xd3, 0xcf, 0x2a, 0x34, 0x59, 0xb1, 0x48, 0xb6, 0x38, 0x01, 0xb8, 0x5f, 0x93,
	0xf7, 0xc6, 0x04, 0x76, 0xe4, 0xf1, 0xcb, 0x19, 0x76, 0xe5, 0x49, 0x1b, 0xf1, 0x0f, 0xef, 0xa0,
	0xf3, 0x40, 0x76, 0x9f, 0x67, 0xb0, 0x2f, 0xbf, 0xf7, 0x18, 0xa2, 0xfc, 0x51, 0x23, 0x53, 0xce,
	0xa0, 0x77, 0xa2, 0x9c, 0x3f, 0x3d, 0xe2, 0xb9, 0xf4, 0xb5, 0xcc, 0xbf, 0xcd, 0x4e, 0xda, 0x3b,
	0x10, 0x65, 0xff, 0x5b, 0xe8, 0x2f, 0xbc, 0x35, 0xad, 0xd2, 0x90, 0x16, 0x56, 0xd9, 0xf4, 0x0f,
	0xba, 0xb9, 0x67, 0x03, 0xbd, 0xf9, 0x9d, 0x6e, 0xd9, 0xe0, 0xdf, 0xe4, 0xe6, 0x2b, 0x00, 0x00,
	0xff, 0xff, 0xce, 0x06, 0x16, 0x21, 0x6c, 0x02, 0x00, 0x00,
}
