// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: email/email.proto

package email

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/go-iot-platform/go-micro/api"
	client "github.com/go-iot-platform/go-micro/client"
	server "github.com/go-iot-platform/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for EmailSvc service

func NewEmailSvcEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for EmailSvc service

type EmailSvcService interface {
	Send(ctx context.Context, in *EmailRequest, opts ...client.CallOption) (*EmailResponse, error)
}

type emailSvcService struct {
	c    client.Client
	name string
}

func NewEmailSvcService(name string, c client.Client) EmailSvcService {
	return &emailSvcService{
		c:    c,
		name: name,
	}
}

func (c *emailSvcService) Send(ctx context.Context, in *EmailRequest, opts ...client.CallOption) (*EmailResponse, error) {
	req := c.c.NewRequest(c.name, "EmailSvc.Send", in)
	out := new(EmailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EmailSvc service

type EmailSvcHandler interface {
	Send(context.Context, *EmailRequest, *EmailResponse) error
}

func RegisterEmailSvcHandler(s server.Server, hdlr EmailSvcHandler, opts ...server.HandlerOption) error {
	type emailSvc interface {
		Send(ctx context.Context, in *EmailRequest, out *EmailResponse) error
	}
	type EmailSvc struct {
		emailSvc
	}
	h := &emailSvcHandler{hdlr}
	return s.Handle(s.NewHandler(&EmailSvc{h}, opts...))
}

type emailSvcHandler struct {
	EmailSvcHandler
}

func (h *emailSvcHandler) Send(ctx context.Context, in *EmailRequest, out *EmailResponse) error {
	return h.EmailSvcHandler.Send(ctx, in, out)
}
