// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simple-notification/message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/micro/go-micro/api/proto"
	calling "github.com/go-iot-platform/rbac/proto/calling"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotifyRequest struct {
	Thing          *calling.Thing `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Gateway        *calling.Thing `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Template       *calling.Thing `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	Zone           *calling.Thing `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	CustomerNumber string         `protobuf:"bytes,5,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	// notification type are below
	// DoorSensor
	// MotionSensor
	// SecurityBreach
	// SafetyBreachCO
	// SafetyBreachSOS
	// SafetyBreachSmoke
	// SecurityAlarm
	// SafetyAlarm
	Type                 int32                 `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Value                string                `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	MacAddress           string                `protobuf:"bytes,8,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	ClientConfig         *calling.ClientConfig `protobuf:"bytes,9,opt,name=clientConfig,proto3" json:"clientConfig,omitempty"`
	Email                string                `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NotifyRequest) Reset()         { *m = NotifyRequest{} }
func (m *NotifyRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyRequest) ProtoMessage()    {}
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{0}
}

func (m *NotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRequest.Unmarshal(m, b)
}
func (m *NotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRequest.Marshal(b, m, deterministic)
}
func (m *NotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRequest.Merge(m, src)
}
func (m *NotifyRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyRequest.Size(m)
}
func (m *NotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRequest proto.InternalMessageInfo

func (m *NotifyRequest) GetThing() *calling.Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

func (m *NotifyRequest) GetGateway() *calling.Thing {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *NotifyRequest) GetTemplate() *calling.Thing {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *NotifyRequest) GetZone() *calling.Thing {
	if m != nil {
		return m.Zone
	}
	return nil
}

func (m *NotifyRequest) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *NotifyRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NotifyRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *NotifyRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *NotifyRequest) GetClientConfig() *calling.ClientConfig {
	if m != nil {
		return m.ClientConfig
	}
	return nil
}

func (m *NotifyRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Request struct {
	Thing          *calling.Thing `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Gateway        *calling.Thing `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Template       *calling.Thing `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	Zone           *calling.Thing `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	CustomerNumber string         `protobuf:"bytes,5,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	MacAddress     string         `protobuf:"bytes,8,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	// notification type are below
	// DoorSensor
	// MotionSensor
	// SecurityBreach
	// SafetyBreachCO
	// SafetyBreachSOS
	// SafetyBreachSmoke
	// SecurityAlarm
	// SafetyAlarm
	Type                 int32    `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetThing() *calling.Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

func (m *Request) GetGateway() *calling.Thing {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *Request) GetTemplate() *calling.Thing {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *Request) GetZone() *calling.Thing {
	if m != nil {
		return m.Zone
	}
	return nil
}

func (m *Request) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *Request) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *Request) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetNotificationRequest struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Serial               string   `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNotificationRequest) Reset()         { *m = GetNotificationRequest{} }
func (m *GetNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*GetNotificationRequest) ProtoMessage()    {}
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{2}
}

func (m *GetNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotificationRequest.Unmarshal(m, b)
}
func (m *GetNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotificationRequest.Marshal(b, m, deterministic)
}
func (m *GetNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotificationRequest.Merge(m, src)
}
func (m *GetNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_GetNotificationRequest.Size(m)
}
func (m *GetNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotificationRequest proto.InternalMessageInfo

func (m *GetNotificationRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetNotificationRequest) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

type GetNotificationResponse struct {
	Success              bool                  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage         string                `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Data                 []*NotificationResult `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetNotificationResponse) Reset()         { *m = GetNotificationResponse{} }
func (m *GetNotificationResponse) String() string { return proto.CompactTextString(m) }
func (*GetNotificationResponse) ProtoMessage()    {}
func (*GetNotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{3}
}

func (m *GetNotificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotificationResponse.Unmarshal(m, b)
}
func (m *GetNotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotificationResponse.Marshal(b, m, deterministic)
}
func (m *GetNotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotificationResponse.Merge(m, src)
}
func (m *GetNotificationResponse) XXX_Size() int {
	return xxx_messageInfo_GetNotificationResponse.Size(m)
}
func (m *GetNotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotificationResponse proto.InternalMessageInfo

func (m *GetNotificationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetNotificationResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetNotificationResponse) GetData() []*NotificationResult {
	if m != nil {
		return m.Data
	}
	return nil
}

type NotificationResult struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ThingName            string   `protobuf:"bytes,2,opt,name=thingName,proto3" json:"thingName,omitempty"`
	ThingSerial          string   `protobuf:"bytes,3,opt,name=thingSerial,proto3" json:"thingSerial,omitempty"`
	ThingDisplayName     string   `protobuf:"bytes,4,opt,name=thingDisplayName,proto3" json:"thingDisplayName,omitempty"`
	GatewayName          string   `protobuf:"bytes,5,opt,name=gatewayName,proto3" json:"gatewayName,omitempty"`
	GatewayDisplayName   string   `protobuf:"bytes,6,opt,name=gatewayDisplayName,proto3" json:"gatewayDisplayName,omitempty"`
	GatewayMacAddress    string   `protobuf:"bytes,7,opt,name=gatewayMacAddress,proto3" json:"gatewayMacAddress,omitempty"`
	ZoneName             string   `protobuf:"bytes,8,opt,name=zoneName,proto3" json:"zoneName,omitempty"`
	ZoneDisplayName      string   `protobuf:"bytes,9,opt,name=zoneDisplayName,proto3" json:"zoneDisplayName,omitempty"`
	Status               int32    `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Type                 int32    `protobuf:"varint,11,opt,name=type,proto3" json:"type,omitempty"`
	Template             string   `protobuf:"bytes,12,opt,name=template,proto3" json:"template,omitempty"`
	State                int32    `protobuf:"varint,13,opt,name=state,proto3" json:"state,omitempty"`
	Description          string   `protobuf:"bytes,14,opt,name=Description,proto3" json:"Description,omitempty"`
	DescriptionVN        string   `protobuf:"bytes,15,opt,name=descriptionVN,proto3" json:"descriptionVN,omitempty"`
	AlertType            int32    `protobuf:"varint,16,opt,name=AlertType,proto3" json:"AlertType,omitempty"`
	DateTime             string   `protobuf:"bytes,17,opt,name=DateTime,proto3" json:"DateTime,omitempty"`
	Acknowledged         int32    `protobuf:"varint,18,opt,name=Acknowledged,proto3" json:"Acknowledged,omitempty"`
	AlertStatus          int32    `protobuf:"varint,19,opt,name=AlertStatus,proto3" json:"AlertStatus,omitempty"`
	DeviceId             int32    `protobuf:"varint,20,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationResult) Reset()         { *m = NotificationResult{} }
func (m *NotificationResult) String() string { return proto.CompactTextString(m) }
func (*NotificationResult) ProtoMessage()    {}
func (*NotificationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{4}
}

func (m *NotificationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationResult.Unmarshal(m, b)
}
func (m *NotificationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationResult.Marshal(b, m, deterministic)
}
func (m *NotificationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationResult.Merge(m, src)
}
func (m *NotificationResult) XXX_Size() int {
	return xxx_messageInfo_NotificationResult.Size(m)
}
func (m *NotificationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationResult.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationResult proto.InternalMessageInfo

func (m *NotificationResult) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NotificationResult) GetThingName() string {
	if m != nil {
		return m.ThingName
	}
	return ""
}

func (m *NotificationResult) GetThingSerial() string {
	if m != nil {
		return m.ThingSerial
	}
	return ""
}

func (m *NotificationResult) GetThingDisplayName() string {
	if m != nil {
		return m.ThingDisplayName
	}
	return ""
}

func (m *NotificationResult) GetGatewayName() string {
	if m != nil {
		return m.GatewayName
	}
	return ""
}

func (m *NotificationResult) GetGatewayDisplayName() string {
	if m != nil {
		return m.GatewayDisplayName
	}
	return ""
}

func (m *NotificationResult) GetGatewayMacAddress() string {
	if m != nil {
		return m.GatewayMacAddress
	}
	return ""
}

func (m *NotificationResult) GetZoneName() string {
	if m != nil {
		return m.ZoneName
	}
	return ""
}

func (m *NotificationResult) GetZoneDisplayName() string {
	if m != nil {
		return m.ZoneDisplayName
	}
	return ""
}

func (m *NotificationResult) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *NotificationResult) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NotificationResult) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *NotificationResult) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *NotificationResult) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NotificationResult) GetDescriptionVN() string {
	if m != nil {
		return m.DescriptionVN
	}
	return ""
}

func (m *NotificationResult) GetAlertType() int32 {
	if m != nil {
		return m.AlertType
	}
	return 0
}

func (m *NotificationResult) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func (m *NotificationResult) GetAcknowledged() int32 {
	if m != nil {
		return m.Acknowledged
	}
	return 0
}

func (m *NotificationResult) GetAlertStatus() int32 {
	if m != nil {
		return m.AlertStatus
	}
	return 0
}

func (m *NotificationResult) GetDeviceId() int32 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func init() {
	proto.RegisterType((*NotifyRequest)(nil), "NotifyRequest")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*GetNotificationRequest)(nil), "GetNotificationRequest")
	proto.RegisterType((*GetNotificationResponse)(nil), "GetNotificationResponse")
	proto.RegisterType((*NotificationResult)(nil), "NotificationResult")
}

func init() { proto.RegisterFile("simple-notification/message.proto", fileDescriptor_94158a4fda103638) }

var fileDescriptor_94158a4fda103638 = []byte{
	// 744 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x55, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xbe, 0x69, 0xf3, 0x7b, 0xda, 0xfc, 0x74, 0x5a, 0xb5, 0xa3, 0xe8, 0xea, 0xde, 0x12, 0x21,
	0xa8, 0x10, 0x75, 0x44, 0x91, 0x60, 0x1d, 0xb5, 0x2a, 0xea, 0xa2, 0x11, 0x72, 0x2b, 0x58, 0x3b,
	0xe3, 0xa9, 0x3b, 0xaa, 0xed, 0x09, 0xf6, 0xb8, 0x55, 0x58, 0xf1, 0x18, 0x3c, 0x13, 0xcf, 0xc1,
	0x5b, 0xb0, 0x61, 0xe6, 0x8c, 0x93, 0xd8, 0x49, 0x11, 0x6c, 0xd9, 0xcd, 0xf7, 0x9d, 0xbf, 0x99,
	0xef, 0x9c, 0x63, 0xc3, 0x93, 0x54, 0x44, 0xd3, 0x90, 0x1f, 0xc7, 0x52, 0x89, 0x1b, 0xc1, 0x3c,
	0x25, 0x64, 0x3c, 0x8c, 0x78, 0x9a, 0x7a, 0x01, 0x77, 0xa6, 0x89, 0x54, 0xb2, 0xff, 0x26, 0x10,
	0xea, 0x36, 0x9b, 0x38, 0x4c, 0x46, 0x43, 0x19, 0xa7, 0x77, 0x33, 0x16, 0xca, 0xcc, 0x1f, 0x26,
	0x13, 0x8f, 0x0d, 0xd1, 0x63, 0xc8, 0xbc, 0x30, 0x14, 0x71, 0xb0, 0x12, 0x77, 0x5c, 0x88, 0x8b,
	0x04, 0x4b, 0xe4, 0x30, 0x90, 0xc7, 0xf6, 0xe0, 0x4d, 0x45, 0x1e, 0xaa, 0x4f, 0xd6, 0x7d, 0xf0,
	0x6d, 0x03, 0xda, 0x63, 0x73, 0x8b, 0x99, 0xcb, 0x3f, 0x65, 0x3c, 0x55, 0xe4, 0x5f, 0xa8, 0xa9,
	0x5b, 0x9d, 0x97, 0x56, 0x0e, 0x2b, 0x47, 0x5b, 0x27, 0x75, 0xe7, 0xda, 0x20, 0xd7, 0x92, 0xe4,
	0x10, 0x1a, 0x81, 0xa7, 0xf8, 0x83, 0x37, 0xa3, 0x1b, 0x25, 0xfb, 0x9c, 0x26, 0x03, 0x68, 0x2a,
	0xae, 0x5f, 0xa7, 0x21, 0xdd, 0x2c, 0xb9, 0x2c, 0x78, 0xd2, 0x87, 0xea, 0x67, 0x19, 0x73, 0x5a,
	0x2d, 0xd9, 0x91, 0x23, 0xcf, 0xa0, 0xc3, 0xb2, 0x54, 0xc9, 0x88, 0x27, 0xe3, 0x2c, 0x9a, 0xf0,
	0x84, 0xd6, 0xb4, 0x57, 0xcb, 0x5d, 0x61, 0x09, 0x81, 0xaa, 0x9a, 0x4d, 0x39, 0xad, 0x6b, 0x6b,
	0xcd, 0xc5, 0x33, 0xd9, 0x83, 0xda, 0xbd, 0x17, 0x66, 0x9c, 0x36, 0x30, 0xc4, 0x02, 0xf2, 0x1f,
	0x40, 0xe4, 0xb1, 0x91, 0xef, 0x27, 0x5a, 0x29, 0xda, 0x44, 0x53, 0x81, 0x21, 0xaf, 0x60, 0x9b,
	0x85, 0x82, 0xc7, 0xea, 0x54, 0xc6, 0x37, 0x22, 0xa0, 0x2d, 0xbc, 0x55, 0xdb, 0x39, 0x2d, 0x90,
	0x6e, 0xc9, 0xc5, 0x14, 0xe2, 0x91, 0x27, 0x42, 0x0a, 0xb6, 0x10, 0x82, 0xc1, 0x8f, 0x0a, 0x34,
	0xfe, 0x36, 0x19, 0x7f, 0x27, 0xce, 0x1f, 0xcb, 0x3c, 0x38, 0x87, 0xfd, 0x77, 0x5c, 0x8d, 0x0b,
	0x23, 0x3d, 0xd7, 0x42, 0xfb, 0x33, 0x99, 0xc5, 0x0a, 0xb5, 0xa8, 0xb9, 0x16, 0x90, 0x7d, 0xa8,
	0xa7, 0x3c, 0x11, 0x5e, 0x88, 0x12, 0xb4, 0xdc, 0x1c, 0x0d, 0xbe, 0x54, 0xe0, 0x60, 0x2d, 0x51,
	0x3a, 0xd5, 0x4b, 0xc0, 0x09, 0x85, 0x46, 0x9a, 0x31, 0x66, 0xae, 0x6a, 0x72, 0x35, 0xdd, 0x39,
	0xd4, 0x7a, 0x6d, 0xf3, 0x24, 0x91, 0xc9, 0xa5, 0xdd, 0x86, 0x3c, 0x67, 0x89, 0x23, 0xcf, 0xa1,
	0xea, 0x7b, 0xca, 0xd3, 0x7a, 0x6e, 0x6a, 0xbd, 0x76, 0x9d, 0x95, 0x12, 0x59, 0xa8, 0x5c, 0x74,
	0x18, 0x7c, 0xad, 0x01, 0x59, 0x37, 0x92, 0x0e, 0x6c, 0x08, 0x3f, 0x7f, 0x84, 0x3e, 0xe9, 0x1e,
	0xb7, 0xb0, 0x9d, 0x63, 0x2f, 0x9a, 0x17, 0x5c, 0x12, 0xba, 0xc7, 0x5b, 0x08, 0xae, 0xec, 0x23,
	0x37, 0xd1, 0x5e, 0xa4, 0xc8, 0x0b, 0xe8, 0x21, 0x3c, 0x13, 0xa9, 0x6e, 0xe8, 0x0c, 0xd3, 0x54,
	0xd1, 0x6d, 0x8d, 0x37, 0xd9, 0xf2, 0xd1, 0x40, 0x37, 0xdb, 0xcc, 0x22, 0x45, 0x1c, 0x20, 0x39,
	0x2c, 0xe6, 0xab, 0xa3, 0xe3, 0x23, 0x16, 0xf2, 0x12, 0x76, 0x72, 0xf6, 0x72, 0x39, 0x00, 0xb6,
	0xa3, 0xeb, 0x06, 0x3d, 0x6b, 0x4d, 0x33, 0x57, 0x98, 0xd3, 0x4e, 0xc9, 0x02, 0x93, 0x23, 0xe8,
	0x9a, 0x73, 0xb1, 0x6c, 0x0b, 0x5d, 0x56, 0x69, 0xec, 0xb9, 0xf2, 0x54, 0x96, 0xe2, 0xe2, 0xd4,
	0xdc, 0x1c, 0x2d, 0xa6, 0x6c, 0xab, 0x30, 0x65, 0xfd, 0xc2, 0x06, 0x6c, 0xdb, 0x8a, 0x8b, 0xc9,
	0xd7, 0x13, 0x65, 0x22, 0x39, 0x6d, 0xdb, 0x89, 0x42, 0x60, 0x34, 0x3a, 0xe3, 0x29, 0x4b, 0xc4,
	0xd4, 0x34, 0x8d, 0x76, 0xac, 0x46, 0x05, 0x8a, 0x3c, 0x85, 0xb6, 0xbf, 0x84, 0x1f, 0xc6, 0xb4,
	0x8b, 0x3e, 0x65, 0xd2, 0xf4, 0x75, 0x14, 0xf2, 0x44, 0x5d, 0x9b, 0x2b, 0xf5, 0xb0, 0xc2, 0x92,
	0x30, 0xf7, 0x3a, 0xd3, 0xd5, 0xae, 0x85, 0x7e, 0xe6, 0x8e, 0xbd, 0xd7, 0x1c, 0x9b, 0x29, 0x1c,
	0xb1, 0xbb, 0x58, 0x3e, 0x84, 0xdc, 0x0f, 0xb8, 0x4f, 0x09, 0x06, 0x97, 0x38, 0x73, 0x4b, 0x4c,
	0x76, 0x65, 0x85, 0xd8, 0x45, 0x97, 0x22, 0x85, 0x15, 0xf8, 0xbd, 0x60, 0xfc, 0xc2, 0xa7, 0x7b,
	0x68, 0x5e, 0xe0, 0x93, 0xef, 0x15, 0xe8, 0x16, 0x47, 0xf3, 0xea, 0x9e, 0x91, 0xff, 0xa1, 0x7e,
	0x9a, 0x70, 0xa3, 0x40, 0xd3, 0xc9, 0x77, 0xae, 0xdf, 0x72, 0xe6, 0x4b, 0x33, 0xf8, 0x87, 0x0c,
	0xa1, 0x67, 0x1d, 0x3e, 0xea, 0x9f, 0x83, 0xfd, 0xdc, 0x93, 0x8e, 0x53, 0xfa, 0xee, 0x97, 0x03,
	0xce, 0xa1, 0xbb, 0xb2, 0x82, 0xe4, 0xc0, 0x79, 0x7c, 0xbb, 0xfb, 0xd4, 0xf9, 0xc5, 0xb6, 0xea,
	0x3c, 0x6f, 0x81, 0xac, 0x18, 0x47, 0xef, 0x2f, 0x48, 0xd7, 0x09, 0xa4, 0x63, 0xfe, 0x41, 0xf3,
	0x14, 0xbd, 0x25, 0x61, 0x43, 0x27, 0x75, 0xfc, 0x3d, 0xbd, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff,
	0x6f, 0x6a, 0x8b, 0xcd, 0x2a, 0x07, 0x00, 0x00,
}
